### PR TITLE
#509: Component Object Pattern, #466 Monitor Object pattern, #564 Collection Pipeline Pattern

### PR DESCRIPTION
**Pull request by nikhilbarar**
An implementation of Component Object Pattern using IBM Selenium.

Added a new module 'component-object'.

### CODE REVIEW

**Comment by nikhilbarar** [comment]
Hi, requesting a review. Please let me know if any changes are required.

**Comment by npathai** [comment]
@nikhilbarar Thanks for the PR :+1: I will review it in a day or two and let you know of any changes.

**Comment by nikhilbarar** [comment]
Thanks @npathai 👍

**Comment by nikhilbarar** [comment]
An implementation of Collection Pipeline Pattern.

Added a new module 'collection-pipeline'.

**Comment by nikhilbarar** [comment]
Apologies for the delay and inconvenience. I've raised 3 separate pull requests #767 #768 #769 for these issues.

Component Object pattern, as per my understanding, is a testing design pattern, which helps us in creating reusable components for end to end testing. The example uses Selenium web driver to create java components representing UI components (fetched using HTML selectors through selenium libraries). It then goes on to demonstrate the reusability of these components in different JUnit test cases.

I believe the user interface can be written in any language but the component creation and their use should remain the same. The interface just helps in demonstrating the use of the pattern.
Please advise.

**Comment by npathai** [comment]
@nikhilbarar Thanks I will close this PR and start reviewing your work.

**Pull request closed without merging**
