### PR TITLE
Fix broken logging in service layer

### PR DESCRIPTION
**Pull request by amit1307**
Pull request title

- Fix broken logging in service layer
- https://github.com/iluwatar/java-design-patterns/issues/1339

Pull request description

- Changes in service-layer `logback.xml` to fix logging

### CODE REVIEW

**Comment by amit1307** [comment]
Hey sorry, couldn't find the exact issue in PR build. I can see the below error but not sure if this can cause the build failure:

`[ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar (default-cli) on project java-design-patterns: You're not authorized to run analysis. Please contact the project administrator. -> [Help 1]`

**Comment by iluwatar** [comment]
It seems SonarQube doesn't work well with pull requests from forks (see https://jira.sonarsource.com/browse/MMF-1371). I'll modify the CI build so that PR from fork does run the analysis.

**Comment by iluwatar** [comment]
@amit1307 can you merge the changes from `master` so we can see if the CI build now works as expected?

**Comment by amit1307** [comment]
Sure, have raised another PR from master.

**Pull request closed without merging**
