### PR TITLE
update distribution for java to 'adpot'

### PR DESCRIPTION
**Pull request by ohbus**
Update `actions/setup-java` actions to **`'adopt'`**

@iluwatar Please add this to master on an urgent basis.

### CODE REVIEW

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Huge thanks @ohbus for the fix

**Comment by ohbus** [comment]
Didn't create any issues while we tested this code, but it is creating errors while executing tests in the `reactor` module.

### _Strange_ 😕

**Comment by iluwatar** [comment]
It is strange. We could create a new issue about this @ohbus if it's not yet resolved.

**Comment by ohbus** [comment]
> It is strange. We could create a new issue about this @ohbus if it's not yet resolved.

Yes it is resolved now, was a problem from GitHub Actions team.

**Pull request merged**
