### PR TITLE
📍Use lombok, reformat, and optimize the code

### PR DESCRIPTION
**Pull request by va1m**
Use lombok

- Replace boiled code by lombok annotations
- #1503

Pull request description

- Use `@Slf4j` instead of LOGGER var definition and initialisation
- Use `@Getter` and `@Setter` instead of vanila java implementations
- Use `@ToString` instead of custom implementations
- Use `@EqualsAndHashcode` instead of manually created `equals()` and `hashCode()`
- Autoformat project java classes
- Remove `public` for test methods using JUnit5

### CODE REVIEW

**Comment by sumitaccess007** [comment]
Hi @iluwatar 
Can I start working on this to refactor the code and use Lombok Library, If yes, please assign to me.

**Comment by va1m** [comment]
> Hi @iluwatar
> Can I start working on this to refactor the code and use Lombok Library, If yes, please assign to me.

Hi @sumitaccess007, this pull request already uses logbook library.

**Comment by va1m** [comment]
@iluwatar, can you please review the PR?

**Review by ohbus — COMMENTED** [review]
This is a very long Pull Request and will take time to get reviewed.

**Review by ohbus — COMMENTED** [review]
I have also seen that you have made changes in Junit code as well.
But have not mentioned it in the PR description.

It would be great if you could provide a solid documentation for each changes in the PR.

**Comment by iluwatar** [comment]
There are conflicts that need to be resolved @va1m

**Review by iluwatar — APPROVED** [review]
The changes look good to me and we can merge it once the conflict have been resolved.

- In the future please keep the pull request scope smaller, for example one PR per pattern would be much easier to review and merge quickly. It takes an hour or two to even read through the changes when there are 692 files changed.
- Try to avoid incorporating unrelated changes in the same pull request. Like here there were hundreds of changes in test files, reformatting and small bug fixes.
- I added a page to our wiki collecting the allowed Lombok annotations: https://github.com/iluwatar/java-design-patterns/wiki/18.-Lombok Please comments if there's something missing that we are using/want to use

**Comment by ohbus** [comment]
@va1m and @iluwatar Please check as I have updated the code removing the merge conflicts as It was pending for a long time even after approval.

Thanks.

**Review by ohbus — CHANGES_REQUESTED** [review]
@va1m Can you please look at what are the changes that is breaking the code.

Thanks.

**Comment by MrR0807** [comment]
Instead of introducing Lombok, use Java 16 and [records](https://openjdk.java.net/jeps/395) wherever possible. Also, be aware that [record builders](https://github.com/openjdk/amber-docs/blob/master/eg-drafts/reconstruction-records-and-classes.md) are also in works.

**Comment by iluwatar** [comment]
> Instead of introducing Lombok, use Java 16 and [records](https://openjdk.java.net/jeps/395) wherever possible. Also, be aware that [record builders](https://github.com/openjdk/amber-docs/blob/master/eg-drafts/reconstruction-records-and-classes.md) are also in works.

Thanks @MrR0807 this looks very interesting development indeed. However, currently the project is on Java 11 level and it will take some time to get us compatible with Java 16. What we can do at this stage is to create an issue about this so we can get back to it at some later stage.

**Comment by ohbus** [comment]
@va1m this PR has been inactive for a long time, we will close it soon if we do not see any updates.

**Comment by va1m** [comment]
@iluwatar I fixed the conflicts but I have no idea how to fix the sonarCloud issue https://sonarcloud.io/project/issues?id=iluwatar_java-design-patterns&open=AXgOdcr_XiJrFJc0KlII&pullRequest=1560&resolved=false&severities=MAJOR&types=CODE_SMELL

**Review by ohbus — COMMENTED** [review]
@va1m you need to provide test cases to increase code coverage.

**Comment by ohbus** [comment]
> @iluwatar I fixed the conflicts but I have no idea how to fix the sonarCloud issue https://sonarcloud.io/project/issues?id=iluwatar_java-design-patterns&open=AXgOdcr_XiJrFJc0KlII&pullRequest=1560&resolved=false&severities=MAJOR&types=CODE_SMELL

I believe this issue can be fixed just by refactoring it into two separate chunks. @va1m

**Comment by va1m** [comment]
> @va1m you need to provide test cases to increase code coverage.

I didn't append new code and code coverage shouldn't being decreased. If it happened then probably it's a SonarQube configuration issue related to lombok and it should be configured accordingly.

Anyway, I have no more time to spend on this pr. Feel free to finish it yourself if you need it.

**Review by ohbus — APPROVED** [review]
Thank you @va1m for your contribution.

We will wait for @iluwatar as he reviews the PR with the conflicts removed.

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
We are extremely thankful for this huge contribution @va1m! I think these numbers tell a great story of how much boilerplate it removed:

image

@all-contributors please add @va1m for code

**Pull request merged**
