### PR TITLE
Some more tests for DAO and Command pattern

### PR DESCRIPTION
**Pull request by iamrichardjones**

### CODE REVIEW

**Comment by iluwatar** [comment]
@iamrichardjones can you catch up your branch from the master? There are conflicts.

**Comment by iamrichardjones** [comment]
Hi, yep just realised this and sorting out now. Sorry about that. Thanks

**Comment by iamrichardjones** [comment]
Hi Iuwatar. It should be up to date now. If it is still a mess just reject and i'll start again. Thanks

**Comment by iluwatar** [comment]
It does not compile unfortunately. Please try again and make another pull request.

**Pull request closed without merging**
