### PR TITLE
Adding Setter Dependency Injection as a second subtype of DI

### PR DESCRIPTION
**Pull request by kapinuss**
There are two types of dependency injection: Constructor dependency injection and Setter Dependency Injection. Both types have pluses and minuses and wide used (f.e. in Spring Framework). This patch describes second type of DI - Setter Dependency Injection. 

Class AdvancedSorceress is constructed by analogy with AdvancedWizard. Difference between them is in the way of dependency injection. Tests attached.

### CODE REVIEW

**Comment by kapinuss** [comment]
I have no idea, why Travis has a problem with this code: all tests on my computer pass well.

**Comment by iluwatar** [comment]
@kapinuss add Checkstyle plugin to your IDE, configure it with `checkstyle.xml` and resolve the style errors.

**Comment by kapinuss** [comment]
@iluwatar ok, i'll try)

**Comment by kapinuss** [comment]
@iluwatar, DONE!))) Thank you for your tips)

**Comment by iluwatar** [comment]
@kapinuss well done! Thank you for the contribution :+1:

**Comment by iluwatar** [comment]
@all-contributors please add @kapinuss for code

**Pull request merged**
