### PR TITLE
Add Bill Pugh Impl & Test

### LINKED ISSUE #187: More Singleton wisdom
Analyze the following article from Oracle: https://community.oracle.com/docs/DOC-918906

Improve Singleton examples and their documentation where necessary.

### PR DESCRIPTION
**Pull request by Owen-CH-Leung**
Add Bill Pugh Implementation & Test. Closes #187

### CODE REVIEW

**Comment by Owen-CH-Leung** [comment]
@iluwatar Can I ask for your review for my PR ? 

I failed at the CI job saying `Error:  Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.2.1:check (validate) on project singleton: You have 9 Checkstyle violations. -> [Help 1]`, but when I run `mvn -e checkstyle:check --projects singleton`, I was only getting 3 Checkstyle violations...

Appreciate your help!

**Review by iluwatar — CHANGES_REQUESTED** [review]
The build is failing due to Checkstyle errors. Check out the build log https://github.com/iluwatar/java-design-patterns/actions/runs/5302826366/jobs/9598037590?pr=2538#step:7:774 You can also reproduce the errors by building locally. IntelliJ IDEA Checkstyle plugin is also useful.

**Comment by Owen-CH-Leung** [comment]
@iluwatar Thanks. I fixed the style issue but CI now fails at the second job...

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Looks good! Thank you for the contribution 🎉

@all-contributors please add @Owen-CH-Leung for code

**Pull request merged**
