### PR TITLE
#1260 add composed-method pattern 

### LINKED ISSUE #1260: Compose Method pattern
https://www.informit.com/articles/article.aspx?p=1398607

### PR DESCRIPTION
**Pull request by wangihzyue**
resolve #1260 .
update new pr.

### CODE REVIEW

**Comment by wangihzyue** [comment]
related pr is [https://github.com/iluwatar/java-design-patterns/pull/1713](https://github.com/iluwatar/java-design-patterns/pull/1713). The original one has some problem on conflicts.

**Review by ohbus — COMMENTED** [review]
Why are making duplicate PRs @wangihzyue for stuff that is already reviewed?

This makes reviewing so much more difficult as we will be doing the same repetitive things again.

Please respect others' time when they are already reviewing your code and never duplicate PRs for which they are already reviewed.

**Comment by wangihzyue** [comment]
I'm really sorry about that. I modify my master branch wrongly and it influence the work to merge as I cannot find the correct ways to resolve the conflicts. I have searched many ways to correct my branch. But they all don't work. I don't know how to resolve these problem. I have pull the request. But my branch shows that I haven't pull the request. I don't know how to resolve the problem. I try all my best to fix the problem. But I have no ability to resolve the conflicts. The conflicts cannot be resolved. So I pull a new request.

**Comment by wangihzyue** [comment]
I search the solution to resolve my problem. I ask somebody else. I try many approaches. But I just cannot fix the problem. I have no idea. So I have to delete the my original master branch and fork the master newly, and pull the request again.

**Comment by wangihzyue** [comment]
This time I will notice my behavior and I avoid the problem I was made. This time, I operate the things correctly.

**Comment by iluwatar** [comment]
@wangihzyue can you confirm that you have corrected all the issues sent to you in the review comments of the earlier pull request https://github.com/iluwatar/java-design-patterns/pull/1713?

**Comment by wangihzyue** [comment]
Yes, I just copy the latest version of my original modified part.

**Pull request closed without merging**
