### PR TITLE
#1324 Use interfaces in command pattern

### PR DESCRIPTION
**Pull request by ravening**
Typically command pattern is implemented using interfaces and concrete classes.
Command interface will have an execute method and other helper methods. The concrete
classes are supposed to implement the command interface.
Refactor the code so that it follows the design

### CODE REVIEW

**Comment by ravening** [comment]
> Also the class diagram needs to be updated. The `urm-maven-plugin` does that for you, just need to generate the picture out of that. See https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute instructions.

Does `mvn clean package` automatically generates new uml diagram?
I changed contents in `command.urm.puml` and ran `mvn clean package` but it didnt generate new png

**Comment by iluwatar** [comment]
> > Also the class diagram needs to be updated. The `urm-maven-plugin` does that for you, just need to generate the picture out of that. See https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute instructions.
> 
> Does `mvn clean package` automatically generates new uml diagram?
> I changed contents in `command.urm.puml` and ran `mvn clean package` but it didnt generate new png

`mvn clean package` generates the new diagram `<pattern>.urm.puml` in the `<pattern>/etc` directory. But you need to create the image from that yourself using one of the tools mentioned in the instructions (new pattern / 7.).

**Comment by ravening** [comment]
> > > Also the class diagram needs to be updated. The `urm-maven-plugin` does that for you, just need to generate the picture out of that. See https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute instructions.
> > 
> > 
> > Does `mvn clean package` automatically generates new uml diagram?
> > I changed contents in `command.urm.puml` and ran `mvn clean package` but it didnt generate new png
> 
> `mvn clean package` generates the new diagram `<pattern>.urm.puml` in the `<pattern>/etc` directory. But you need to create the image from that yourself using one of the tools mentioned in the instructions (new pattern / 7.).

Thanks for the quick reply. In the meanwhile I was able to create new image using intellij

**Comment by iluwatar** [comment]
@all-contributors please add @ravening for code

**Comment by iluwatar** [comment]
@ravening Thank you for your time and valuable first-time contribution to this repository! 👍🏻

**Pull request merged**
