### PR TITLE
Update Pull Requests CI trigger behaviour

### PR DESCRIPTION
**Pull request by ohbus**
# Improve Pull Request trigger behaviour

### Why does it need any improvement?
⛔ Reopened Pull Request will not start to build automatically
⛔ Labelling and unlabelling them will not start a build

### The Pull Request Builder will now automatically get triggered on the following events:
- [x] opened
- [x] reopened
- [x] synchronize
- [x] labeled
- [x] unlabeled

#### These additional behaviours will work on top of the existing behaviour of:
✔️  Opening a new Pull Request.
✔️  Pushing a new commit to existing Pull Request.

### CODE REVIEW

**Comment by ohbus** [comment]
Hey @iluwatar Please review this.

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Thanks @ohbus for this improvement! Since you've done several high quality pull requests already, I'd like to invite you to the core team. Contributor access gives you push access to the repository and makes you able to improve things on your own, review/merge pull requests etc. Of course you'll have my full support where needed. Do you accept?

**Comment by ohbus** [comment]
> Thanks @ohbus for this improvement! Since you've done several high quality pull requests already, I'd like to invite you to the core team. Contributor access gives you push access to the repository and makes you able to improve things on your own, review/merge pull requests etc. Of course you'll have my full support where needed. Do you accept?

Thank you so much for this honour ❤️😄❤️  I'm very delighted to accept your request.

Looking forward to collaborate to make greater things!

**Comment by iluwatar** [comment]
Invites sent and looking forward to collaborate as well. In addition to Github we can use Gitter for chats.

**Pull request merged**
