### PR TITLE
Added Explanation for Combinators pattern along with the benefits #590

### PR DESCRIPTION
**Pull request by dmdbilal**
With the response of the issue #590. I've added the explanation for combinators in its readme.md file. @iluwatar

### CODE REVIEW

**Comment by dmdbilal** [comment]
Can someone explain why i'm failed in the test?. I'm new to open source.

**Comment by iluwatar** [comment]
No worries @dmdbilal, the failure is not caused by your changes.

@ohbus would you have time to look at this:

> [ERROR] Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.8.0.2131:sonar (default-cli) on project java-design-patterns: 
> [ERROR] 
> [ERROR] The version of node.js (12) you have used to run this analysis is deprecated and we stopped accepting it.
> [ERROR] Please update to at least node.js 14. You can find more information here: https://docs.sonarcloud.io/appendices/scanner-environment/

**Review by iluwatar — APPROVED** [review]

**Comment by ohbus** [comment]
I'll take a look this weekend

**Comment by iluwatar** [comment]
@all-contributors please add @dmdbilal for docs

**Comment by iluwatar** [comment]
Created issue https://github.com/iluwatar/java-design-patterns/issues/2054

**Pull request merged**
