### PR TITLE
Upgraded spring-data-jpa and excluded overridden dependencies.

### PR DESCRIPTION
**Pull request by mohanaraosv**
Inspired by the PR https://github.com/iluwatar/java-design-patterns/pull/1856 

It resolves the issue of a security alert in spring data JPA. #978

* I have picked this task to get familiar with the repo. 
* Upgraded the dependencies and excluded since version getting overridden from parent version.  
* Would like to upgrade spring boot and config in the next PR.

### CODE REVIEW

**Comment by iluwatar** [comment]
The task was assigned to @mohanaraosv according to our processes, so I'll reopen this PR

**Comment by iluwatar** [comment]
@mohanaraosv please resolve the conflicts first

**Review by ohbus — CHANGES_REQUESTED** [review]
There is something seriously wrong with this PR.

We are not expecting these many line changes.

Please fix this issue.

**Review by ohbus — CHANGES_REQUESTED** [review]
Still, there are a lot of files that have been altered for just updating a few version numbers. Please check it and revert back if you would need some help.

**Comment by mohanaraosv** [comment]
Created a fresh PR  https://github.com/iluwatar/java-design-patterns/pull/1982

**Pull request closed without merging**
