### PR TITLE
#701 new pattern: efficient_cache_result

### PR DESCRIPTION
**Pull request by zhengzhanpeng**
efficient_cache_result

- Efficient cache result is a high-performance pattern for saving cached results under concurrency conditions

Pull request description

- I want to try to make this model. If there are problems in the code, please point out.

### CODE REVIEW

**Comment by zhengzhanpeng** [comment]
@iluwatar If you have time, I would like to git your suggestion.

**Comment by iluwatar** [comment]
I don't see any changes. Where is the code?

**Comment by zhengzhanpeng** [comment]
image
Here it is.

**Comment by zhengzhanpeng** [comment]
Can't you see that? @iluwatar

**Comment by zhengzhanpeng** [comment]
Sorry, I git.  I  will solve immediately it in two minutes

**Pull request closed without merging**
