### PR TITLE
Maven profiles to support jdk 11 builds. #948

### PR DESCRIPTION
**Pull request by lbroman**
Added maven profiles activated by jdk 11, wich will not break java 8 support.
Bumped lombok and datanucleus enhancer as the old versions dont work with 11.

Pull request title

- Clearly and concisely describes what it does
- Refer to the issue that it solves, if available

Pull request description

- Describes the main changes that come with the pull request
- Any relevant additional information is provided

> For detailed contributing instructions see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

### CODE REVIEW

**Comment by perwramdemark** [comment]
Does this even build on JDK11 ?
data-nucleus needed config changes to work with the new versions. See #959.

**Comment by lbroman** [comment]
I also saw this problem in naked-objects, the problem is from a error threshold in the pmd-plugin. I get this error when building with jdk 8 as well and figured this was an unrelated issue. Are you not seeing this issue when building with jdk 8?

**Comment by lbroman** [comment]
Added a second rules file which fixes the pmd issue. Also, improved the dependencymanagement for jdk11 where I had previously not used dependency management but dependencies.

**Comment by iluwatar** [comment]
@lbroman you are right, the naked-objects problem is an already existing one

**Comment by iluwatar** [comment]
When building with JDK11 on my local machine I get errors in 3 of the patterns. See the picture

image

**Comment by iluwatar** [comment]
Full build output here: 
[build-output.txt](https://github.com/iluwatar/java-design-patterns/files/3718651/build-output.txt)

**Comment by iluwatar** [comment]
@lbroman please merge master so we can see Travis build output on openjdk8 and 11

**Comment by lbroman** [comment]
I have merged master and fixed the eip modules that didn't build properly.

**Comment by iluwatar** [comment]
@lbroman the builds are green :+1: 
Can we update the language level to 11? See https://github.com/iluwatar/java-design-patterns/issues/976 and https://winterbe.com/posts/2018/08/29/migrate-maven-projects-to-java-11-jigsaw/#configure-plugins-for-java-11

**Comment by lbroman** [comment]
I suggest merging this PR first then make a new PR with change in language level, remove the jdk 8 travis builds and move the jdk11 specific profiles to top level dependencies in the maven poms.

**Comment by iluwatar** [comment]
No problem, we can proceed with that approach. @lbroman can you create the new issue with the acceptance criteria you specified?

**Comment by iluwatar** [comment]
Actually I realized we can just reuse the same issue so no action needed there

**Pull request merged**
