### PR TITLE
Override annotation added

### PR DESCRIPTION
**Pull request by slawiko**
I think this is a typo

### CODE REVIEW

**Comment by iluwatar** [comment]
In my opinion it is good to have the `@Override` annotation when implementing interface methods. This way we can utilize compiler checks to verify that the implementing method signature really matches the interface and is not a new method. We could enforce this with Checkstyle i.e. Checkstyle would give an error if interface method implementation would not specify `@Override`. @slawiko @npathai what do you think?

**Comment by slawiko** [comment]
@iluwatar I thought it was already in your Checkstyle. Howbeit we MUST add it in checkstyle :)

**Comment by iluwatar** [comment]
@slawiko it is not there yet, otherwise the build would not work. Maybe it is this one: http://checkstyle.sourceforge.net/config_annotation.html#MissingOverride Could you try adding it and see what happens?

**Comment by slawiko** [comment]
@iluwatar yes of course, but not right now.

**Comment by iluwatar** [comment]
No problem, just let us know then.

**Comment by slawiko** [comment]
@iluwatar as I understood `<module name="MissingOverride"/>` works only if code contains JavaDoc tag `{@inheritDoc}`. But if I add this tag Imgur code inspection with Imgur still passes checkstyle: Imgur. I use Checkstyle for the first time, so I can be wrong. By the way, I tried without JavaDoc tag `{@inheritDoc}`, but result was identical. What do I do wrong?

**Comment by iluwatar** [comment]
Looks like `MissingOverride` is not what we want. I'm not sure if Checkstyle has exactly what we need.

**Comment by iluwatar** [comment]
My suspicion is verified in http://checkstyle.sourceforge.net/google_style.html

"6.1 @Override: always used" - "That validation could not be checked by Checkstyle. It's need to take a look as parent class. But Checkstyle have no way open or look at another Class file. "

**Comment by iluwatar** [comment]
Thanks @slawiko for the improvement!

**Comment by slawiko** [comment]
@iluwatar you're welcome!

**Pull request merged**
