### PR TITLE
#176 Added new pattern - EIP Wire Tap

### PR DESCRIPTION
**Pull request by codinghog**
New pattern added - EIP Wire Tap.
- Added new directory - eip-wire-tap
- Added sources for wire tap pattern
- Added tests
- Added description to README.md file

### CODE REVIEW

**Comment by codinghog** [comment]
I wanted to create fully working EIP context. `App.java` sets up and starts Spring Boot application, which takes care of adding all the routes to the context. I can refactor it by dropping Spring Boot, setting up Apache Camel context by hand, running routes and terminating the app.

However, test for `App.java` will test only if there were any exceptions thrown during the execution. Do you want any tests for the route? I have checked the Message Channel pattern and there are no tests for actual route, only for `App.java` execution.

**Comment by iluwatar** [comment]
> However, test for App.java will test only if there were any exceptions thrown during the execution

Yes, this is fine. Not sufficient testing alone, but it is a good addition to test that all our examples run correctly.

> Do you want any tests for the route? I have checked the Message Channel pattern and there are no tests for actual route, only for App.java execution.

It is a big bonus if you can do that. I'm not that experienced with Camel and couldn't do that with Message Channel example.

**Comment by codinghog** [comment]
Ok. I'll refactor `App.java` a little and add a test for it.

**Comment by codinghog** [comment]
I have made changes according to your requirements. Unfortunately the build fails because of some test errors in `throttling` project. Any ideas?

**Comment by iluwatar** [comment]
@codinghog is your branch up-to-date with master? A fix was made to Throttling pattern a while ago, see https://github.com/iluwatar/java-design-patterns/issues/643

**Comment by codinghog** [comment]
@iluwatar All tests passed, changes made as you have requested

**Comment by iluwatar** [comment]
Good job @codinghog! Thanks for the contribution :+1:

**Pull request merged**
