### PR TITLE
Attempt to solve issue #292

### PR DESCRIPTION
**Pull request by JuhoKang**
I changed the example and added a little scenario. But not sure if this is a good example to understand the adapter pattern. Please give me some feedback.

### CODE REVIEW

**Comment by iluwatar** [comment]
- [ ] Put `under review` badge to the pull request
- [ ] Check that the code compiles and the existing tests succeed
- [ ] Does the example code implement the pattern correctly and follow good coding practices?
- [ ] Does the example code have proper tests and enough test coverage?
- [ ] Is the example code commented well enough?
- [ ] Is the example code following JavaDoc conventions?
- [ ] Are the project [coding conventions](https://github.com/iluwatar/java-design-patterns/wiki/3.-Coding-conventions) being followed?
- [ ] Is the class diagram generated correctly?
- [ ] Is the `index.md` implemented correctly so the pattern will show correctly on the web site?
- [ ] Is the originator of the design pattern properly credited?

**Comment by iluwatar** [comment]
@JuhoKang you have my review comments. Please comment on this thread when you've made the minor changes. Great work overall!

**Comment by JuhoKang** [comment]
Thanks! I forgot to reformat the codes of some files so I made the changes that you told me. Please check.
I'm glad you liked the story :D.

**Comment by iluwatar** [comment]
Thank you @JuhoKang for this contribution :smiley:

**Pull request merged**
