### PR TITLE
Unit tests for adapter, business-delegate, factory-method and command modules

### PR DESCRIPTION
**Pull request by mfarid**
This pull request contains unit tests for the following modules.

* adapter
* business-delegate
* factory-method
* command

The existing tests were more of Exercise Tests which were just running the code and printing the output. This code was not asserting the expected behaviour. This Pull Request covers the code to 100% of lines of these 4 patterns. The code coverage report can be generated and viewed using the instructions mentioned in CODE_COVERAGE.md

Please let me know in case of any issues/concerns.

Mohd Farid
DevFactory - Open Source Unit Test Team

[DevFactory] (https://github.com/DevFactory/) is committed to improving code quality of open source. Our team contributes their time to researching and identifying areas for improving test coverage of open source projects.

### CODE REVIEW

**Comment by iluwatar** [comment]
Here are my review remarks:

- The code should be formatted to use Google coding conventions as described in the [developer wiki](https://github.com/iluwatar/java-design-patterns/wiki/03.-Coding-conventions)
- Do you think we still need the old `AppTest` classes? Does the coverage drop if we remove the old tests?

**Comment by iluwatar** [comment]
This is all for now. Please comment on this thread once you have made the changes and I will review again.

**Comment by mfarid** [comment]
I have made the suggested changes. I look forward to your review comments.

**Comment by iluwatar** [comment]
Hi @mfarid I looked at it again. It is all great except that the code is still not formatted according to Google rules. Can you check once more?

**Comment by mfarid** [comment]
I have formatted all these files using the suggested code style. Please check again and let me know if it is good now or needs any changes.

**Comment by iluwatar** [comment]
Looks good, thank you!

**Comment by faridiflex** [comment]
Thanks a lot for accepting this Pull Request. I appreciate your quick review and feedback.

**Comment by npathai** [comment]
Thanks for your contribution @faridiflex

**Pull request merged**
