### PR TITLE
Thread-Local Storage mechanism

### PR DESCRIPTION
**Pull request by Regyl**
Implements issue https://github.com/iluwatar/java-design-patterns/issues/2265

### CODE REVIEW

**Comment by iluwatar** [comment]
@Regyl please note that there already is an implementation of the thread local storage pattern in `tls` subfolder. I'm not sure if you knew about that and wanted to replace the example?

**Comment by Regyl** [comment]
@iluwatar sorry, didn't know TLS already implemented. In the older version almost nothing that my version wouldn't have had, so can I just delete it?
Or maybe combine into one folder, didn't find anything about this case in project's wiki.

**Comment by iluwatar** [comment]
@Regyl It's ok to replace the old example with this new one. Just delete the `tls` folder and remove the reference from the parent pom.xml.

**Comment by Regyl** [comment]
@iluwatar fixed it

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Looks good! Thank you for the contribution 🎉

@all-contributors please add @Regyl for code

**Pull request merged**
