### PR TITLE
Finite state machine

### PR DESCRIPTION
**Pull request by stephen-lazarionok**

### CODE REVIEW

**Comment by npathai** [comment]
I will pick it up this weekend. As agreed in #221 I request you to format the code according to Google Style guide.

**Comment by noobxgockel** [comment]
Your diagram seems non-standard. Please use the method mentioned in the readme
> For creating/editing UML diagrams you need ObjectAid UML Explorer for Eclipse.

It doesnt look bad but we want unity here. If you dont like the current way the diagrams are displayed then you are welcome to suggest other tools to create UML diagrams from source here #190

**Comment by stephen-lazarionok** [comment]
@noobxgockel I do not have Eclipse installed... Could anybody help me and create a diagram from the classes I have?

@npathai I will format the code according to Google Style guide and will check in my changes.

**Comment by iluwatar** [comment]
- add finite-state-machine as a module to the super pom.xml
- tests are missing
- diagram is non-standard

**Comment by iluwatar** [comment]
Looking at the paper http://www.csee.wvu.edu/~ammar/rts/adv%20rts/statecharts%20patterns%20papers%20and%20%20examples/paper%20on%20state%20pattern%20B31-full.pdf and comparing it to the example I fail to see similar class structure. In the paper Context and States implement the same interface but in the example this seems to be not so.

I think Context should have references to the states and be responsible for State transitions. In the example there is FiniteStateMachine containing Context and method for State transitions.

**Comment by geniusgeek** [comment]
I read the paper and it was very interesting especially the state data
model, the Context , more importantly, the event abstraction transition and
Automation interface, but i still feel that we could do better. The problem
with their implementation is that the states have to be know in advanced,
and users may not find it easy adding states. Also i feel that the events
should be implemented as commands, so as to avoid declaring no-ops
methods(or methods we don't need in each state). The concept of data
abstraction(using data model) is fine with memory(no memory consideration
as to excess storage of state data) but what if data changes in each state
or if each state need explicit data or to return to previous state and
remember previous data{ for this i feel that the data model should be
implemented using a memento pattern}. With these few issues in mind, i feel
we can write a great implementation of the pattern.

**Comment by geniusgeek** [comment]
please i need comment based on my suggestion above. Also is anyone still
working on this pattern. or can i take it up?

**Comment by iluwatar** [comment]
I've provided my comments to @stephen-lazarionok The current review status is as follows.

- [X] Put under review badge to the pull request
- [ ] Does the example code implement the pattern correctly?
- [ ] Does the example code have enough test coverage?
- [ ] Is the example code commented well enough?
- [ ] Is the example code following JavaDoc conventions?
- [ ] Are the project coding conventions being followed?
- [ ] Is the class diagram generated correctly?
- [ ] Is the index.md implemented correctly so the pattern will show correctly on the web site?

If there is no activity anymore on this PR I will close it this weekend and @geniusgeek can take it up.

**Comment by npathai** [comment]
@iluwatar see comment of Stephen on PR of active record pattern.. He seems to be on a vacation.

**Comment by iluwatar** [comment]
Thanks @npathai Ok, we can then wait a few more days. Maybe we can establish some sort of guideline from this, how long the PR's are kept open.

**Comment by npathai** [comment]
@iluwatar yes we can raise this point on chat room .

**Comment by iluwatar** [comment]
Due to no activity for 30 days I'm closing this PR.

**Comment by geniusgeek** [comment]
@iluwatar please i will start an activity on this as stated i am taking this up and will be active in in two days time.

**Comment by iluwatar** [comment]
Just comment on the issue https://github.com/iluwatar/java-design-patterns/issues/203 that you are working on it and when you're ready, create a pull request. This one is closed.

**Comment by geniusgeek** [comment]
ok

**Pull request closed without merging**
