### PR TITLE
#970 single logging framework should be enforced

### PR DESCRIPTION
**Pull request by jjjimenez100**
Replaces all usages of log4j with the Slf4j API. This PR also removes references of log4j in pom and resource files.

### CODE REVIEW

**Comment by iluwatar** [comment]
@jjjimenez100 please resolve the conflict

**Comment by jjjimenez100** [comment]
Fixed by [bf2b3cb](https://github.com/iluwatar/java-design-patterns/pull/982/commits/bf2b3cbffccaf21c5493109f862ed8f7e0ea321b) Although I'm not really sure that was the best way to fix the conflict since I did it on Ghub's UI. :sweat_smile:

**Comment by jjjimenez100** [comment]
> The changes look good, but log4j is still present in several places. You can try to grep the codebase like `grep -r -l "log4j"` to see where it is still referenced.

Ah right. About that, I think the only remaining are the ones under the `naked-objects` pattern. However, it seems like Apache ISIS' `withLoggingAt(..);` only accepts the concrete class of log4j's `Level`. Should I simply just remove that line?

**Comment by iluwatar** [comment]
It's ok for me to remove those statements. It would be also good to scan for `System.out.println` style logging. I think I've seen some of those in the codebase.
There are some conflicts now that should be resolved.

**Comment by jjjimenez100** [comment]
The only remnants of `System.out...` now would be on:

- The `Composite` pattern
- `ConsoleLoggerModule` 

since the examples has test cases asserting the output from the console (which I believe the way the example was structured to begin with)

For the log4j ones, stuffs remaining are on `persistor.properties` and all of them are already commented.

Let me know if there are any other changes I should do. :smile:

**Comment by iluwatar** [comment]
Thanks @jjjimenez100 for the hard work you've done

**Pull request merged**
