### PR TITLE
Issue #286: Added main method in Abstract Factory Example

### PR DESCRIPTION
**Pull request by tainarareis**
I think it would be better to rename the App class to something like: Factory Producer. And the main method should be in the real App file as unique method. What do you think?

### CODE REVIEW

**Comment by iluwatar** [comment]
I agree with your refactoring proposal. I will accept if you make another PR for that.

**Comment by iluwatar** [comment]
This looks good. Thank you for the help!

**Comment by tainarareis** [comment]
Thank you for accepting! Witch tool do you use for making class diagrams? Is it free?

**Comment by iluwatar** [comment]
It is described in the developer wiki, here https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

**Pull request merged**
