### PR TITLE
 Data Transfer Object pattern 

### PR DESCRIPTION
**Pull request by arindam7development**
I have added an implementation for **Data Transfer Object pattern** . 

**Transfer Object** is a simple POJO class having getter/setter methods and is serializable so that it can be transferred over the network. It does not have any behavior. Server Side business class normally fetches data from the database and fills the POJO and send it to the client or pass it by value.
Please review the changes .

**Class Diagram for Data Transfer Object pattern** data-transfer-object-pattern

### CODE REVIEW

**Comment by npathai** [comment]
Ok thanks. We will review it at the earliest. Following points will be reviewed.
- [X] Put `under review` badge to the pull request
- [ ] Check that the code compiles and the existing tests succeed
- [ ] Does the example code implement the pattern correctly and follow good coding practices?
- [ ] Does the example code have proper tests and enough test coverage?
- [ ] Is the example code commented well enough?
- [ ] Is the example code following JavaDoc conventions?
- [ ] Are the project [coding conventions](https://github.com/iluwatar/java-design-patterns/wiki/3.-Coding-conventions) being followed?
- [ ] Is the class diagram generated correctly?
- [ ] Is the `index.md` implemented correctly so the pattern will show correctly on the web site?
- [ ] Is the originator of the design pattern properly credited?

**Comment by iluwatar** [comment]
Please read [how to contribute](https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute). It has detailed instructions telling what we expect from code.

Here are some findings:
- the module has not been added to main `pom.xml`
- the module itself does not have `pom.xml`
- the class diagram is non-standard
- the pattern has no tests
- `index.md` does not follow the standard structure

**Comment by npathai** [comment]
@arindam7development please follow the guidelines. We will start with code review.

**Comment by npathai** [comment]
@iluwatar I am unaware of the pattern will read abt it and start review. Have you gone through the pattern?

**Comment by npathai** [comment]
@arindam7development Any updates?

**Comment by iluwatar** [comment]
@arindam7development this pull request is about to expire if there is no action during the next few days

**Comment by npathai** [comment]
Closing this PR due to inactivity.

**Pull request closed without merging**
