### PR TITLE
Refactor Prototype pattern

### LINKED ISSUE #584: Prototype pattern re-factor
Hi,

The Prototype implementations where clone() is Overridden (ElfBeast, ElfMage etc) can rather not have implementation of clone(). Instead their respective parent class (Mage, Beast) can have a general implementation of clone which creates a new instance by doing a shallow copy (Object.clone()) and then subsequently type-cast to the type of class (Mage.class or Beast.class etc) it is cloning for. 

This will have advantage of:

1. Removing verbosity among all implementations and dedicate the responsibility of cloning the object by their respective interfaces (abstract class).

2. Avoid using 'new' more than once and using only whilst cloning the prototype object that is passed in HeroFactoryImpl.

Regards,
panksy2k

### PR DESCRIPTION
**Pull request by ThexXTURBOXx**
This PR refactors parts of the Prototype pattern by making it `Cloneable` and thus inheriting the `clone()` method to its subclasses.

- Fixes #584

### CODE REVIEW

**Review by yonatankarp — COMMENTED** [review]
@iluwatar I can pick this one up ☝️

**Comment by iluwatar** [comment]
Ok @yonatankarp

**Review by yonatankarp — COMMENTED** [review]
There's open PR for this issue here: https://github.com/iluwatar/java-design-patterns/pull/1970 We can close this one...

**Comment by iluwatar** [comment]
Ok @yonatankarp, I'll close this one

**Pull request closed without merging**
