### PR TITLE
Replace elasticlunr with lunr as it allows wildcard searches #607

### PR DESCRIPTION
**Pull request by danielsiwiec**
Addresses issue #607

### CODE REVIEW

**Comment by iluwatar** [comment]
Looks like the original issue (https://github.com/iluwatar/java-design-patterns/issues/607) is resolved with this pull request and searching for `prototype` gives only one correct result.

However it seems that some other searches are broken. Testing results for searches
- `caching` gives no results
- `cqrs` gives no results
- `api gateway` gives 9 results

@danielsiwiec can you reproduce this? The search behaves very oddly for me.

**Comment by danielsiwiec** [comment]
@iluwatar I think I finally figured it out - the lunrj stemmer was to blame for this (a component that maps all words added to the index to their base form - e.g. 'caching' -> 'cach'). This was also likely messing up cqrs and these searches should look good now.

For the 'API Gateway' - the reason it shows multiple results is that the other results have 'API' in their content.
We could be more restrictive and either:
a) search only in tags and titles
b) set a threshold for score (each search result comes back with a score, that quantifies how precise the search 'hit' is)

**Comment by iluwatar** [comment]
@danielsiwiec it looks much better now and finds the correct pattern :+1: Still I'm bit confused why it displays multiple results in some cases
- searching for `api` gives 9 results e.g. Aggregator Microservices is one of them, why? It doesn't have `api` in the pattern name.
- searching for `command` gives 2 results, the correct one and CQRS, why?
- searching for `state` gives 14 results (including the correct one), why?

**Comment by danielsiwiec** [comment]
@iluwatar the reason for those additional results to show is that their content (the actual pattern page) contains those keywords. To prevent this, we can disable the content (pattern pages) from being indexed and used in the search.
I think a reasonable approach is to search the names, tags and categories only. Thought?

**Comment by iluwatar** [comment]
@danielsiwiec yes, I think we should disable the content then. The search is more like a filter, not a Google search.

**Comment by danielsiwiec** [comment]
@iluwatar done. Left the title, category and tags to be searchable

**Comment by iluwatar** [comment]
Works perfectly. Thanks @danielsiwiec this is hugely appreciated! :+1:

**Pull request merged**
