### PR TITLE
#1243 - added all <plugins> elements inside the <pluginManagement> element in the pom.xml file of the base project

### PR DESCRIPTION
**Pull request by aryanveer**
Description - 

- There were 2 `<plugins>` elements inside the `<build>` elements of the pom.xml in base project. One the the <plugins> element was inside `<pluginManagement>` element but the other one was outside. I just made those 2 `<plugins>` elements as one and added the whole inside the `<pluginManagement>` element.

- I took help from here https://www.genuitec.com/forums/topic/pom-error-plugin-execution-not-covered-by-lifecycle/
Here it is mentioned : 
**"This is an M2eclipse problem. You are seeing it in MyEclipse as Maven4MyEclipse depends on M2Eclipse.
Add `<pluginManagement>` to pom.xml just above the `<plugins>` element to make the error go away."**

### CODE REVIEW

**Review by iluwatar — CHANGES_REQUESTED** [review]
Thanks @aryanveer, please resolve the conflict.

**Comment by aryanveer** [comment]
> Thanks @aryanveer, please resolve the conflict.

Hi @iluwatar, resolved the merge conflicts.

**Comment by iluwatar** [comment]
I'm very suspicious about the proposed change. There is a clear semantic difference between `pluginmanagement` and `plugins` sections. The `pluginmanagement` is there to list plugins that can then be invoked in the child projects. The `plugins` section contains actual invocations of the plugins. I doubt the build works the same if we move things from `plugins` under `pluginmanagement`.

**Comment by iluwatar** [comment]
See for example here: https://stackoverflow.com/questions/10483180/what-is-pluginmanagement-in-mavens-pom-xml

**Comment by aryanveer** [comment]
@iluwatar I am sharing 2 screenshots:
1. First one is of the master branch which is without any changes in the pom.xml.
Screenshot 2020-09-15 at 12 49 25 AM
Here you can see errors in the Maven which are mentioned in the issue #1243 due to parent pom.xml.

2. This is the screenshot of my issue#1243 branch, which contains my changes where I have moved `plugins` elements inside `pluginManagement`.
Screenshot 2020-09-15 at 1 00 28 AM
Now the errors in the above image have been removed.

**Comment by iluwatar** [comment]
@aryanveer there was a build error in master branch causing also the build of this PR to fail. Could you merge the changes from master so we can see the build result?

**Comment by aryanveer** [comment]
> @aryanveer there was a build error in master branch causing also the build of this PR to fail. Could you merge the changes from master so we can see the build result?

Hi, I'll try to do this in a couple of days.

**Review by iluwatar — CHANGES_REQUESTED** [review]
Although it may remove the error/warning messages in Eclipse, this change can't be approved because it breaks the intended functionality. Moving the plugins to `pluginManagement` section effectively disables the plugin executions. For example the `urm-maven-plugin` is never executed since it's not referenced in the submodules.

**Comment by ohbus** [comment]
@aryanveer can confirm the change in behaviour of the comments that @iluwatar has left for you in [this](https://github.com/iluwatar/java-design-patterns/pull/1518#pullrequestreview-536803347) review.

This PR has been inactive for a long time, we will close it soon if we do not see any updates.

Thank You.

**Pull request closed without merging**
