### PR TITLE
PR for Document design principles #208

### PR DESCRIPTION
**Pull request by npathai**
I have added a Getting started section in README. I was thinking we should add more to this section guiding new comers on how to go about reading and understanding patterns.

We can introduce `Difficulty-Beginner`, `Difficulty-Intermediate`, `Difficulty-Expert`  tags and tag patterns based on their difficulty level so that beginners can have better clarity on which patterns should be read first. Do you think its a good idea @iluwatar @noobxgockel ?

### CODE REVIEW

**Comment by iluwatar** [comment]
:+1:

**Comment by npathai** [comment]
@iluwatar I have added the ways in which a user can explore our design patterns. Anything else to do here? If not then we can merge this.

**Comment by noobxgockel** [comment]
Sounds good to me :+1: 
Cant think of anything missing atm

**Comment by npathai** [comment]
Okie then I will mege this.. Don't know why coverage is failing though..

**Comment by iluwatar** [comment]
Strange it is, with the coverage...

**Pull request merged**
