### PR TITLE
add CII Best Practices badge

### PR DESCRIPTION
**Pull request by zafarella**
* add CII Best Practices badge
* resolves https://github.com/iluwatar/java-design-patterns/issues/672

### CODE REVIEW

**Comment by iluwatar** [comment]
Thanks @zafarella :+1:

**Comment by iluwatar** [comment]
@zafarella can you create issue/issues to satisfy the missing badge requirements?

https://bestpractices.coreinfrastructure.org/projects/1503

**Comment by zafarella** [comment]
@iluwatar  #683

**Comment by Mp5A5** [comment]
mute the thread


On 12/27/2017 01:13，Ilkka Seppälä<notifications@github.com> wrote：

@zafarella can you create issue/issues to satisfy the missing badge requirements?

https://bestpractices.coreinfrastructure.org/projects/1503

**Pull request merged**
