### PR TITLE
add draft presentation for the singleton #197

### PR DESCRIPTION
**Pull request by zafarella**
As per discussion at #197

### CODE REVIEW

**Comment by zafarella** [comment]
note ready yet. Pls wait a bit to finish it.

**Comment by zafarella** [comment]
Take a look guys, how will you like it. Happy to address any issues/dislikes/mistakes.
Thanks

**Comment by iluwatar** [comment]
What I did was go to the presentation directory and start Python web server

`python -m SimpleHTTPServer`

Then open browser and go to `http://localhost:8000`

**Comment by iluwatar** [comment]
It would be nice to reuse portions of the data that we already have in `index.md`.

**Comment by noobxgockel** [comment]
Hmmm... We could automate the process of generating the presentation with the data visible on the website. I highly doubt it would be a good presentation though... We (or more like mr. penguin here) could create presentations manually. The only problem with that would be that is allways out of date, because our repo is changing/adding patterns rapidly.

Dont let yourself be held down @zafarella. But in my honest opinion it wouldnt have much of a use. I only recall learning about patterns in a presentation while i was learning scala (monads, monadics). Presentations are, for me atleast, to be presented by a real person while clicking through the slides.

But if you want to, i can help you integrate your Presentations into the website C:

**Comment by zafarella** [comment]
@noobxgockel thanks for the comments. This is exactly for the making presentation by a person. Sometimes you don't have time to prepare a presentation, but the material already exists, you just need to deliver it to audience. This is why I thought about having in this collection presentation, so you can just open it and start the class.

In regards the outdates - I think we can maintain it, there is no better option so far that I can think of.

@iluwatar you don't really need to run a server - just open the html file in browser. I will reuse the content of index.md.

I think would be better to move presentation and the file into etc directory. Will do that. Also what do you think if there will be umbrella (presentation) file with all patterns somewhere in the root folder.

**Comment by iluwatar** [comment]
Let us know when you are ready for review.

**Comment by zafarella** [comment]
I will try to fix reading the code into HTML page from file(s) and it is ready to be reviewed. Although I am not an HTML expert)

**Comment by iluwatar** [comment]
There has been no progress during the last 30 days, so I will close this PR as expired.

**Pull request closed without merging**
