### PR TITLE
fix issue 1968 and correct visitor pattern code and test.

### PR DESCRIPTION
**Pull request by xyllq999**
This PR helps for solving #1968 

fix issue 1968 and correct visitor pattern code

Modified issue with visitor mode code, changed different method name to method reload, fixed issue1968.

Pull request description

The main modification of the method in the class is visit, which is accessed only by different parameter types, eliminating some errors and simplifying code writing, in line with the pattern requirements.

### CODE REVIEW

**Comment by xyllq999** [comment]
> This PR helps for solving #1968
> 
> fix issue 1968 and correct visitor pattern code
> 
> Modified issue with visitor mode code, changed different method name to method reload, fixed issue1968.
> 
> Pull request description
> 
> The main modification of the method in the class is visit, which is accessed only by different parameter types, eliminating some errors and simplifying code writing, in line with the pattern requirements.

**Comment by yonatankarp** [comment]
Hi @xyllq999 please keep in mind that the README code needs to be updated as well

**Review by yonatankarp — APPROVED** [review]

**Review by yonatankarp — COMMENTED** [review]
Obviously I cannot approve it, but I'll close my PR 🙈

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Many thanks for implementing this improvement @xyllq999! Kudos to @yonatankarp for raising the issue and providing review help.

**Comment by iluwatar** [comment]
@all-contributors please add @xyllq999 for code
@all-contributors please add @yonatankarp for review

**Comment by iluwatar** [comment]
@all-contributors please add @xyllq999 for code

**Comment by iluwatar** [comment]
@all-contributors please add @yonatankarp for review

**Comment by iluwatar** [comment]
@all-contributors please add @yonatankarp for review

**Pull request merged**
