### PR TITLE
Translated the business delegate pattern into Chinese

### PR DESCRIPTION
**Pull request by Al-assad**

### CODE REVIEW

**Review by ohbus — APPROVED** [review]
Thanks, @Al-assad for your contribution.

**Comment by ohbus** [comment]
@all-contributors please add @Al-assad for translation

**Comment by Al-assad** [comment]
> @all-contributors please add @Al-assad for translation

Thank you, I plan to translate the rest of it next.
It's a great project and I hope to introduce it to more Chinese developers

**Comment by ohbus** [comment]
> Thank you, I plan to translate the rest of it next.
> It's a great project and I hope to introduce it to more Chinese developers

Looking forward to it.

**Pull request merged**
