### PR TITLE
Add checkstyle into maven

### PR DESCRIPTION
**Pull request by zafarella**
This will add checkstyle plugin. It will not fail the build, but print warnings.
Align with styles could be done in separate branch.

### CODE REVIEW

**Comment by noobxgockel** [comment]
In case you didnt know:
https://google.github.io/styleguide/javaguide.html#s2.3.1-whitespace-characters
TL;DR Java devs hate Tabs, dont ask me why...
Thats also why travis fails.

**Comment by zafarella** [comment]
travis failed because log is too long and it assumed that this is due to test failure.
Local `mvn validate` successes but bunch of warnings, coz code is not styled according rules.

**Comment by zafarella** [comment]
Should I do you think reformat java files according to styling guides?

**Comment by noobxgockel** [comment]
Ohh now i get it... didnt think travis would fail just because the file is too large.
Well you couldnt possible format all the code, thats a huge task, but i'd suggest muting all the warnings and only printing the error (if thats possible with the maven checkstyle plugin).

We dont really need the warnings when travis is building the thing right?
I hope im right :S

**Comment by iluwatar** [comment]
Please catch up the branch with origin/master and I will review. Is there an issue for this?

**Comment by zafarella** [comment]
Synced with master. Please note that checkstyle is "off" and will not report anything. Each java file need to be aligned according to the rules of checkstyle. It can be turned on by switching flag to `<consoleOutput>false</consoleOutput>` to `true`.

**Comment by npathai** [comment]
Yes once we format all code we will set the flag

**Comment by iluwatar** [comment]
Thanks @zafarella

**Pull request merged**
