### PR TITLE
Fix ko(README.md) - update badges, Add Links

### PR DESCRIPTION
**Pull request by behappyleee**
Fix ko README.md 
Update badge images (invisible image),
Add Links to move another translated languages.

Thank you for your effort.
It is really helpful to study design patterns.
Thank you so much.

### CODE REVIEW

**Review by yoavami — APPROVED** [review]
Changes look good.

**Comment by behappyleee** [comment]
> Changes look good.

Thanks ! I updated branch ! 

Thank you for your review !

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
@all-contributors please add @behappyleee for translation

**Comment by iluwatar** [comment]
@behappyleee thank you for the fix 👍

**Pull request merged**
