### PR TITLE
Dep: remove mongodb uber artifact

### PR DESCRIPTION
**Pull request by robertvolkmann**
`spring-boot-dependencies` already provides the same artifacts as `org.mongodb.mongo-java-driver`.

### CODE REVIEW

**Comment by robertvolkmann** [comment]
Why are the tests `MongoBankTest`, `MongoTicketRepositoryTest`, and `MongoEventLogTest` disabled? What about using an embedded Mongo database or mocking the `MongoClient`?

**Comment by iluwatar** [comment]
> `spring-boot-dependencies` already provides the same artifacts as `org.mongodb.mongo-java-driver`.

Ok, in that case this is a good technical improvement to remove the duplication

**Comment by iluwatar** [comment]
> @iluwatar Why are the tests `MongoBankTest`, `MongoTicketRepositoryTest`, and `MongoEventLogTest` disabled? What about using an embedded Mongo database or mocking the `MongoClient`?

I suppose the tests need a real MongoDB installed before they can run. What you suggest sounds like a good way forward. I'll create a new ticket about it.

**Review by iluwatar — CHANGES_REQUESTED** [review]
@robertvolkmann could you please resolve the conflicts and we can merge this?

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Looks good! Thank you for the contribution 🎉

**Pull request merged**
