### PR TITLE
#88 add facet pattern new version

### LINKED ISSUE #88: Facet pattern
http://www.hillside.net/plop/plop2002/final/plop2002_ecrahen0_0.pdf

### PR DESCRIPTION
**Pull request by wangihzyue**
resolve #88 .
new version.

### CODE REVIEW

**Comment by wangihzyue** [comment]
The original pr has some problem on conflict. So I create a new pr. The original pr is [https://github.com/iluwatar/java-design-patterns/pull/1717](https://github.com/iluwatar/java-design-patterns/pull/1717)

**Comment by iluwatar** [comment]
@wangihzyue it's not a good idea to abandon the original pull request just because there's a conflict. Normally you just merge the `master` branch to your branch and resolve the conflicts. By closing the old pull request we lose all the review work done so far. Can you confirm that you have addressed all the review comments in https://github.com/iluwatar/java-design-patterns/pull/1717 in this pull request?

**Comment by wangihzyue** [comment]
e, well, I download the final version of my original pull request and copy my part to this new pull request.

**Comment by wangihzyue** [comment]
And my original forked repository has been deleted.

**Comment by iluwatar** [comment]
Well, you can still see the review comments we gave at https://github.com/iluwatar/java-design-patterns/pull/1717. Please verify that you have done all the requested changes and then ask for another review.

**Comment by ohbus** [comment]
> The original pr has some problem on conflict. So I create a new pr. The original pr is #1717

If you ever face conflicts just discuss with the maintainers of the repository if you find it difficult to resolve them.

Asking for help is always appreciated.
Ask for Help

**Pull request closed without merging**
