### PR TITLE
Sonar report - fix blocker and critical ones

### PR DESCRIPTION
**Pull request by interactwithankush**
- sonar report :- [here](https://sonarcloud.io/project/issues?id=iluwatar_java-design-patterns&resolved=false&severities=BLOCKER&types=CODE_SMELL)

- PR raised against issue :- [SonarCloud reports issues #1012](https://github.com/iluwatar/java-design-patterns/issues/1012)

Change description :-
- fixed Sonar blocker and critical issues related to duplicate String literals
- Refer to the issue that it solves, if available

Pull request description

- fixed Sonar blocker and critical issues related to duplicate String literals
- removed unnecessary empty default constructor

### CODE REVIEW

**Comment by interactwithankush** [comment]
@iluwatar @ohbus Kindly review

**Comment by interactwithankush** [comment]
Please put review comments as needed
@iluwatar @ohbus

**Comment by interactwithankush** [comment]
@ohbus  @iluwatar . I am done with my changes. Kindly review.

**Review by ohbus — CHANGES_REQUESTED** [review]
Thank you so much for your interest in our project.

I would request if you could please increase the Code COverage to at least 80%

Thanks!

**Comment by interactwithankush** [comment]
Hi @ohbus . Thanks for allowing me to contribute in this well kept repo to help serve the java community.
While removing some blocker & critical bugs reported by sonar, I have also tried adding a Test class to cover as much as I could. The original issue was about fixing sonar bugs. And while I fixed those, sonar somehow annotated those existing lines as new ones, and is expecting to have test cases for all of them. I have tried to bring it up to 50%. I guess that is the best I could do for this PR. I can pick up test coverage as a separate PR, and while not digressing from the objective of  this PR. Do let know if there is any specific review for this PR. Thanks.

**Comment by interactwithankush** [comment]
@ohbus  Is there any review comment I can help with before merging this PR?

**Comment by interactwithankush** [comment]
@ohbus @iluwatar Please review :)

**Comment by interactwithankush** [comment]
@iluwatar @ohbus
Please help complete review this PR - #1899
It has been waiting under review for a long time

**Review by ohbus — COMMENTED** [review]
So far so good. Thank you so much for the improvement this looks very promising and you have really put a lot of effort into this.

I would still want you to look into this code smell as it has come up and would really appreciate it if you could please help resolve this.

**Comment by interactwithankush** [comment]
Hi @ohbus . 
Last code smell is cleaned in latest. Thanks.

**Comment by interactwithankush** [comment]
Hi @ohbus 
Just curious about when could we expect this PR to get merged?

**Comment by interactwithankush** [comment]
I guess the build is failing because "SonarCloud is under maintenance"
image

**Comment by interactwithankush** [comment]
Hi @ohbus . The changes you asked for have been incorporated.
Please add if there are any more comments on this PR.

**Comment by interactwithankush** [comment]
@ohbus
All requested changes are completed. Kindly review the PR.

**Comment by interactwithankush** [comment]
Hi @ohbus  @iluwatar 
Being a time bound activity, could you please complete the review process.

**Comment by interactwithankush** [comment]
@ohbus @iluwatar  Waiting for review & merge :)

**Comment by ohbus** [comment]
This is Open Source and people here contribute out of their passion during their free time for which they are almost never rewarded.

Please do not mention us repeatedly for the same thing which spams our notification for something which we have in our mind when you pushed your commit.

Currently we may not have the bandwidth to accommodate these requests, as maintaiers might be busy with something else.

Please have some patience, we will do our due diligence in due course of time.

**Comment by interactwithankush** [comment]
Hi @ohbus 
Just a peaceful reminder. I do not intend to spam. Thx

**Comment by interactwithankush** [comment]
@ohbus  Hope this long pending PR is taken up soon 👍

**Review by ohbus — APPROVED** [review]
Thank you so much for your efforts @interactwithankush

**Comment by ohbus** [comment]
@all-contributors please add @interactwithankush for code

Thank you for your patience. This has been long due.

**Pull request merged**
