### PR TITLE
fixed issue #681

### PR DESCRIPTION
**Pull request by jujis008**
fixed the diagram bug and merge two pictures as one

- Clearly and concisely describes what it does
As reporter says there has one error on the diagram, I've repaint the UML diagram and merge them together which make it clean and clear.

Pull request description

- Describes the main changes that come with the pull request
fixed the error and deleted unrelation pictures and files
- Any relevant additional information is provided

### CODE REVIEW

**Comment by jujis008** [comment]
@iluwatar The abstract-document.ucls is a xml file to generate UML picture, because they will generate wrong UML picture if keep old UCLS files, besides, I'm using another UML tool which cannot generate such a file. I could download the plugin and repaint the UML with UCLS file if you really need it.

**Comment by iluwatar** [comment]
You should include the updated `abstract-document.ucls` that is the source for `abstract-document.png` you are uploading.

**Comment by jujis008** [comment]
okay.

**Comment by jujis008** [comment]
Aha, that's my bad. Already commit the changes, thanks a lot you point out the mistakes.

**Comment by iluwatar** [comment]
Thanks for fixing this @jujis008 :smile:

**Pull request merged**
