### PR TITLE
issue 1628 handled, removed mutex and semaphore from catalog.

### PR DESCRIPTION
**Pull request by rohit10000**
# removed mutex and semaphore from the catalogue.

### CODE REVIEW

**Review by iluwatar — CHANGES_REQUESTED** [review]
The build is failing due to the modules still existing in the main`pom.xml`

**Comment by rohit10000** [comment]
Is there any other issue except for the modules still existing in the mainpom.xml. I removed the modules.

**Review by lilangelrey99 — APPROVED** [review]

**Review by lilangelrey99 — CHANGES_REQUESTED** [review]
> #

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Solves https://github.com/iluwatar/java-design-patterns/issues/1628

**Comment by iluwatar** [comment]
@all-contributors please add @rohit10000 for code

**Pull request merged**
