### PR TITLE
Add missing word to README.md

### PR DESCRIPTION
**Pull request by dsibilio**
Add missing word in README.md sentence.

### CODE REVIEW

**Review by akashchandwani — APPROVED** [review]
LGTM

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
I'm not a native speaker but I trust @akashchandwani helpful review that this is really needed.

**Comment by iluwatar** [comment]
Thanks @dsibilio for the contribution and @akashchandwani for the review help.

**Comment by iluwatar** [comment]
@all-contributors please add @dsibilio for doc

**Comment by iluwatar** [comment]
@all-contributors please add @akashchandwani for review

**Pull request merged**
