### PR TITLE
switch maven  to gradle

### PR DESCRIPTION
**Pull request by jiahut**
### switch the build tool from `maven` to `gradle`

the `pom.xml` is verbose

### CODE REVIEW

**Comment by npathai** [comment]
@iluwatar Switching to gradle should be a good step forward. What are your thoughts?

**Comment by iluwatar** [comment]
@npathai while I don't have anything bad to say about Maven I think Gradle is the more modern build solution. Great comparison available at https://gradle.org/maven-vs-gradle/. I think we can do the switch after a thorough review.

**Comment by iluwatar** [comment]
@jiahut there are some conflicts that should be resolved

**Comment by jiahut** [comment]
@iluwatar had updated the code, there is no problem performing the following build locally
> gradle build  test -x :serverless:test -x :naked-objects:naked-objects-integtests:test

as now the  `:serverless` module and the  `:naked-to-objects:naked-to-integtests` module might use some of the maven plug-ins and need to be fixed.

But the travis-ci lose  with `apt-get install failed`,it is confusing.

**Comment by iluwatar** [comment]
@jiahut the build is failing
```
:serverless:compileJava UP-TO-DATE
:serverless:processResources UP-TO-DATE
:serverless:classes UP-TO-DATE
:serverless:compileTestJavawarning: unknown enum constant Status.STABLE
  reason: class file for org.apiguardian.api.API$Status not found
1 warning
:serverless:processTestResources NO-SOURCE
:serverless:testClasses
:serverless:test
com.iluwatar.serverless.faas.api.LambdaInfoApiHandlerTest > initializationError FAILED
    org.mockito.exceptions.base.MockitoException
        Caused by: java.lang.reflect.InvocationTargetException
            Caused by: org.junit.runners.model.InitializationError
com.iluwatar.serverless.baas.api.SavePersonApiHandlerTest > classMethod FAILED
    java.lang.NoClassDefFoundError
        Caused by: java.lang.ClassNotFoundException
com.iluwatar.serverless.baas.api.FindPersonApiHandlerTest > classMethod FAILED
    java.lang.NoClassDefFoundError
        Caused by: java.lang.ClassNotFoundException
3 tests completed, 3 failed
:serverless:test FAILED
FAILURE: Build failed with an exception.
```

**Comment by jiahut** [comment]
@iluwatar 
fixed the `:serverless` module, unhappy that `:naked-to-objects:naked-to-integtests` module only part of the test passed,  it still have some problems work with  `JDO`,  ignore the test temporarily.
there is no problem performing the following build locally:
> gradle build

But the travis-ci lose with some environmental problem.

**Comment by jiahut** [comment]
@iluwatar 
It work well with performing the following build locally: 
> gradle build test

```

> Task :naked-objects:naked-objects-integtests:datanucleusEnhance
Enhancing with DataNucleus the following files
/Users/admin/develop/java-design-patterns/naked-objects/integtests/build/classes/java/test/domainapp/dom/modules/simple/SimpleObjectsTest$Create$1.class
/Users/admin/develop/java-design-patterns/naked-objects/integtests/build/classes/java/test/domainapp/dom/modules/simple/SimpleObjectTest$Name.class
/Users/admin/develop/java-design-patterns/naked-objects/integtests/build/classes/java/test/domainapp/dom/modules/simple/SimpleObjectsTest$ListAll$1.class
/Users/admin/develop/java-design-patterns/naked-objects/integtests/build/classes/java/test/domainapp/dom/modules/simple/SimpleObjectsTest$ListAll.class
/Users/admin/develop/java-design-patterns/naked-objects/integtests/build/classes/java/test/domainapp/dom/modules/simple/SimpleObjectsTest$Create.class
/Users/admin/develop/java-design-patterns/naked-objects/integtests/build/classes/java/test/domainapp/dom/modules/simple/SimpleObjectTest.class
/Users/admin/develop/java-design-patterns/naked-objects/integtests/build/classes/java/test/domainapp/dom/modules/simple/SimpleObjectsTest.class
[ant:datanucleusenhancer] Java Result: 1

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3s
491 actionable tasks: 1 executed, 490 up-to-date
```

> gradle --version
```
------------------------------------------------------------
Gradle 4.8.1
------------------------------------------------------------

Build time:   2018-06-21 07:53:06 UTC
Revision:     0abdea078047b12df42e7750ccba34d69b516a22

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_151 (Oracle Corporation 25
``

**Comment by iluwatar** [comment]
@jiahut I am able to build the project with `./gradlew clean build` but in the build output I see lots of warnings like this
```
> Task :strategy:compileTestJava
warning: unknown enum constant Status.STABLE
  reason: class file for org.apiguardian.api.API$Status not found
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.EXPERIMENTAL
8 warnings
```

All the Maven build files still seem to be there. Are they still necessary? I'm thinking that with this task we should drop support for Maven and use only Gradle.

Can you provide short instructions for building the project with Gradle? We should use the Gradle wrapper, right?
- How to build the project with all the submodules
- How to build + test the project with all the submodules
- How to build a single submodule
- How to build and test a single submodule

**Comment by iluwatar** [comment]
This pull request is about to be closed due to inactivity

**Pull request closed without merging**
