### PR TITLE
A Warning for beginners in the Readme.

### PR DESCRIPTION
**Pull request by mafagafogigante**
There is a lot of hype about design patterns, and this repository does not have a single KISS or YAGNI warning (at least I haven't seen one).

There is a lot of complex expositions of patterns that a beginner may think he or she must memorize before actually developing something slightly more complicated and no reminders beside the link in Getting Started that they are not mandatory. I thought we needed to have a paragraph directly oriented to DPs right on the readme. I think that that subsection would be the best place for it, but we can discuss that.

The text is adapted from [this (very related) post](http://blog.codinghorror.com/head-first-design-patterns/). Maybe we could even link to it somewhere.

### CODE REVIEW

**Comment by noobxgockel** [comment]
:+1: Patterns can be a trap!
Maybe you could mention what you mentioned here in the PR in the readme itself.
Like concrete stuff, else the beginner might get confused on what to use instead of patterns.
Some links to good articles and Wikipedia wouldn't hurt too :grin:

**Comment by mafagafogigante** [comment]
Can you give me an example of what you meant by "concrete stuff"? I think that it can be elaborated further if that is what you guys want. Feel free to contribute with links and text modifications.

**Comment by noobxgockel** [comment]
concrete stuff:

> KISS or YAGNI

or

> [this (very related) post](http://blog.codinghorror.com/head-first-design-patterns/)

The warning is allready very helpful and nice, adding more info/links/reasoning to it will only make it perfect!

**Comment by mafagafogigante** [comment]
Oh, OK. Will look into it.

**Comment by mafagafogigante** [comment]
I think it is better now. I've mentioned the three first principles on the link that was already there - so I didn't add too much - and also moved it to where I think it fits best.

**Comment by mafagafogigante** [comment]
@iluwatar Can this have your attention? Would you disagree with any of the ideas on that paragraph?

**Comment by iluwatar** [comment]
I'm sorry for the delay. I agree with the point it is making, but I would still reformat the text a little. We should strive to make the text kind and helpful. Probably I would leave out the words beginner and warning at least. I will try to come up with some suggestions.

**Comment by mafagafogigante** [comment]
No problem. I agree that beginner could be changed.

**Comment by mafagafogigante** [comment]
## A word of caution
One should be aware that all designs should be as simple as possible.
Complexity and patterns should only be used where they are *needed for practical
extensibility*. See the KISS, YAGNI, and Do The Simplest Thing That Could
Possibly Work principles in the link above before considering using design
patterns.

@iluwatar What do you say? It is more neutral this way.

**Comment by iluwatar** [comment]
@mafagafogigante How about putting the warning inside the `Getting started` section? Something like this:

## Getting started

Before you dive into the material, you should be familiar with various Programming/Software Design Principles.

All designs should be as simple as possible. You should start with KISS, YAGNI, and Do The Simplest Thing That Could Possibly Work principles. Complexity and patterns should only be introduced when they are needed for practical extensibility.

Once you are familiar with these concepts you can start drilling down into patterns by any of the following approaches

- Using difficulty tags, Difficulty-Beginner, Difficulty-Intermediate & Difficulty-Expert.
- Using pattern categories, Creational, Behavioral and others.
- Search for a specific pattern. Can't find one? Please report a new pattern here.

**Comment by mafagafogigante** [comment]
I think that works. Will amend and push later.

**Comment by Mansuro** [comment]
How can I use the mentioned tags? 'Difficulty-beginner', etc.

**Comment by mafagafogigante** [comment]
See the Tags part of this page http://java-design-patterns.com/patterns/.

**Comment by mafagafogigante** [comment]
@iluwatar Not trying to force you to eventually merge this, but I don't like it unresolved, and don't see why not to merge it as it currently is.

**Comment by iluwatar** [comment]
Sorry @mafagafogigante I haven't noticed the last commit. I only get notifications from PR comments.

This looks ready to merged now.

**Comment by mafagafogigante** [comment]
Yes, that makes sense. Thank you.

**Pull request merged**
