### PR TITLE
Package patterns into executable jars setup

### PR DESCRIPTION
**Pull request by hbothra15**
Package patterns into executable jars

- In this PR i have tried to create the base structure in parent pom and try to implement for abstarct document, if everything looks good then can replicate the same to other packages as well.
- This PR will resolve the issue#989 partially and if approved will do the required changes for other as well

Pull request description

- This PR will have change in parent pom where we have steup the plugin managment for maven assembley plugin and leveraging the same for abstract-document pattern

### CODE REVIEW

**Comment by hbothra15** [comment]
Fixed the conflict

**Comment by hbothra15** [comment]
Hi @iluwatar ,
I would like to know, how to handle patterns which are having sub modules withing them like api-gateway, aggregator-microservices

As of now I have set plugin in each sub module to generate respective jar

**Comment by iluwatar** [comment]
@hbothra15 that is the correct approach. In the microservices example we have 3 submodules that should each be runnable using `java -jar ...`. Aggregator service requires that information and inventory microservices are running so that it can fetch some information from them.

**Comment by hbothra15** [comment]
If there is no conflict can we proceed with first MR, and I will be raising others in batches

**Comment by iluwatar** [comment]
Thanks @hbothra15 for the first set.

**Comment by iluwatar** [comment]
https://github.com/iluwatar/java-design-patterns/issues/989

**Pull request merged**
