### PR TITLE
Add tutorial links to patterns

### PR DESCRIPTION
**Pull request by vaibhav-if**
Pull request title

- Add tutorial links to patterns
- Partially Solves #525 

Pull request description

- Will add tutorial links to the following pattern's readme.md -
1. API-Gateway
2. Model-View-Controller
3. DAO
4. Data-Transfer-Object
5. Data-Mapper

> For detailed contributing instructions see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

### CODE REVIEW

**Review by ohbus — CHANGES_REQUESTED** [review]
Thank you so much for your contribution.

Please collate these changes into a Single PR as it achieves the same thing. We would want to keep the commit log in our `master` branch to a minimum.

Please do mention the list of Patterns in that PR of which you have added the Tutorial links.

Looking forward to your cooperation.

Thanks.

**Comment by vaibhav-if** [comment]
Hi @ohbus, I will make the changes.

Please guide me a little.

What I need to do is merge all my branches from which I made PRs into one and squash all the commits into one, right?

So the end result should be like 1 PR and 1 commit (containing all the changes), or should it be like 1 PR and incremental commits into it (1 commit for 1 pattern)?

Thank You!!

**Comment by ohbus** [comment]
Yes you may **cherry pick** all the commits to one of the existing branch and use it by updating the Title and the description. And close all the other PRs

OR

You may close all the PRs and then cerry pick all the commits to a new branch and raise a new PR

**Comment by vaibhav-if** [comment]
Thanks for guiding me @ohbus, I have made the requested changes in this branch itself and closed other PRs.

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Apologies for leaving your pull request hanging @vaibhav-if Looks like @ohbus left the ship.

@all-contributors please add @vaibhav-if for docs

**Pull request merged**
