### PR TITLE
Code refactoring

### PR DESCRIPTION
**Pull request by ShivanshCharak**
Pull request title

Code Refactored reduced cognitive complexity from 42 to 15

Pull request description
Link of the issue
https://sonarcloud.io/project/issues?id=iluwatar_java-design-patterns&open=AW3G0WIhwB6UiZzQNqtw&resolved=false&severities=CRITICAL

> For detailed contributing instructions see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

### CODE REVIEW

**Review by iluwatar — CHANGES_REQUESTED** [review]
The build is failing, apparently due to Checkstyle issues.

**Comment by ShivanshCharak** [comment]
So it is my issue or server side if my issue can I fix it

**Comment by ShivanshCharak** [comment]
Actually I am done with other critical issue too so should I reduce the checkstyle issue is it my part or should I just raise a pr with all those checksum issues

**Comment by iluwatar** [comment]
`Error:  Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:3.1.0:check (validate) on project acyclic-visitor: You have 1 Checkstyle violation.`

**Comment by iluwatar** [comment]
Please fix the errors reported by Checkstyle @ShivanshCharak

**Comment by iluwatar** [comment]
Closed due to inactivity

**Pull request closed without merging**
