### PR TITLE
updated to switch expression

### PR DESCRIPTION
**Pull request by jeffmorrison**
## What problem does this PR solve?

Updated the bytecode design pattern to the updated switch expression. remove the redundant breaks.

### CODE REVIEW

**Review by jaypalarora — APPROVED** [review]
Reviewed

**Review by Ritabrata1080 — APPROVED** [review]

**Comment by Dibyajyoti1515** [comment]
good change

**Comment by Ritabrata1080** [comment]
Please squash the commits before merging to keep linear history on master. Changes LGTM.

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Looks good! Thank you for the contribution 🎉

@all-contributors please add @jeffmorrison for code

**Pull request merged**
