### PR TITLE
Use logger from Lombok

### PR DESCRIPTION
**Pull request by amit1307**
Introduce Lombok

- This is first PR of many related to Lombok introduction. In this one logger from lombok is added.
- https://github.com/iluwatar/java-design-patterns/issues/1503

### CODE REVIEW

**Comment by divyakumarjain** [comment]
Please see https://github.com/amit1307/java-design-patterns/pull/1. I have added all the loggers and also the branch is building without checkstyle, compiling, unit test failures.

**Comment by amit1307** [comment]
> Please see [amit1307#1](https://github.com/amit1307/java-design-patterns/pull/1). I have added all the loggers and also the branch is building without checkstyle, compiling, unit test failures.

Thanks for that, have merged it.

**Comment by amit1307** [comment]
@iluwatar Hope you are well, would you be happy to merge this PR? It's a first part of the lombok introduction, since there will be huge number of files changes so I thought it would be good add them in small bits. We can still keep the issue open since we would be doing more work related to this.

**Review by iluwatar — CHANGES_REQUESTED** [review]
@amit1307 Thanks for looking into this. Please resolve the conflict first.

**Comment by ohbus** [comment]
@amit1307 Can you please confirm if you are still working on to resolve the conflicts.

This PR has been inactive for a long time, we will close it soon if we do not see any updates.

**Pull request closed without merging**
