### PR TITLE
File renaming (index.md to README.md)

### PR DESCRIPTION
**Pull request by slawiko**
All index.md files renamed to README.md for more compatibility with github

### CODE REVIEW

**Comment by slawiko** [comment]
I renamed these files with following python script:
```python
import os

class RenameFileFromTo:
	def __init__(self, root, filename, new_filename):
		self.root = root
		self.filename = filename
		self.new_filename = new_filename

	def rename(self):
		for root, dirs, files in os.walk(self.root):
			for file in files:
				if file == self.filename:
					os.rename(root + '/' + file, root + '/' + self.new_filename)

RenameFileFromTo(root_to_java-design-patterns, 'index.md', 'README.md').rename()
```

**Comment by npathai** [comment]
Ping @iluwatar . What do you think about this? Should we change the convention?

@markusmo3 Does this change affect our website?

**Comment by iluwatar** [comment]
@slawiko can you list the benefits of this? I can think of browsing the Github repository e.g. https://github.com/iluwatar/java-design-patterns/tree/master/abstract-factory and then Github would show the contents of the `README.md` automatically.

**Comment by markusmo3** [comment]
Yes this would affect the website. But no huge changes would have to be made to make it work with README.md files.

It would improve readability on github([as seen here](https://github.com/slawiko/java-design-patterns/tree/slawiko-patch-1/callback)), so people that dont like our 'beautiful' website with its 'awesome' features could still browse on github

:+1: from me

If @iluwatar and @npathai are okay with this i'll take over this issue

**Comment by iluwatar** [comment]
@markusmo3 it's ok for me

**Comment by slawiko** [comment]
@iluwatar yes, you're right. It's only for improve readability on github. For example I do not browse your website in general, because for me github - most comfortable place for this.

**Comment by slawiko** [comment]
@iluwatar @markusmo3 @npathai oh, I forgot one thing. We should change [developer wiki](https://github.com/iluwatar/java-design-patterns/wiki): all mention of file `index.md`.

**Comment by markusmo3** [comment]
Tested it locally and to my own surprising i dont have to change anything.
Jekyll should work with any *.md files as long as their respective YAML front matter is correct.

**Comment by npathai** [comment]
@markusmo3 Awesome. :+1: 
@slawiko Thanks for the PR.

**Comment by iluwatar** [comment]
@slawiko I see @markusmo3 already made the changes for developer wiki so this should be in order. Good work guys :+1:

**Comment by slawiko** [comment]
@iluwatar @markusmo3 @npathai Thank you, guys. This was my first submitted pull request. THANKS!

**Pull request merged**
