### PR TITLE
Pull Request - Builder Pattern

### PR DESCRIPTION
**Pull request by jrxxjr**
Create a new form for the builder pattern.

### CODE REVIEW

**Comment by npathai** [comment]
@jrxxjr Please provide details of how your change improves on existing code or how is it useful.

**Comment by jrxxjr** [comment]
Your question, is referent to at file Readme.md or the comments in the top of the class ?

**Comment by jrxxjr** [comment]
Ilkka, you removed my commits. Please, as i make this comment that the Narendra asked, it must be done in the file Readme of the Git, or in the Javadoc of the class that i changed ?

**Comment by jrxxjr** [comment]
Ilkka, i had not read of your messages.

**Comment by npathai** [comment]
@jrxxjr First I will suggest to put details in the Pull Request explaining how your improvement helps existing code. And then if the change is accepted we can update the javadoc and README

**Comment by jrxxjr** [comment]
The way i did, the execution of the pattern builder, with the static method, you do not need to instantiate the class. It is referenced by the name of the class, like any other type of static method.
Serves to receive a parameter object, such as a TO for example, and return a VO, populated, or otherwise.
And applies this pattern, in this way, in my understanding, so that the filling out of the object to be done within the object created or referenced statically, without polluting the rest of the code with this, it becomes more clear and organized the encoding.

**Comment by jrxxjr** [comment]
If it is abstracted the pattern builder,to a class apart, is more organized and stylish. And in many projects that I worked was used as well. 

public class BuildWarrior {

  public static Warrior buildWarrior(final Profession profession, final String name,
      final HairType hairType, final HairColor hairColor, final Armor armor, final Weapon weapon) {

    Warrior result = new Warrior();

    if (profession == null || name == null) {
      result = null;
      throw new IllegalArgumentException("profession and name can not be null");
    }
    result.setProfession(profession);
    result.setName(name);
    result.setHairType(hairType);
    result.setHairColor(hairColor);
    result.setArmor(armor);
    result.setWeapon(weapon);

    return result;
  }

  public static WarriorTO build(final Warrior warrior) {

    WarriorTO result = new WarriorTO();

    if (warrior == null) {
      result = null;
      throw new IllegalArgumentException("warrior can not be null");
    }
    
    if (warrior.getProfession() == null || warrior.getName() == null) {
      result = null;
      throw new IllegalArgumentException("profession and name can not be null");
    }
    
    result.setProfession(warrior.getProfession());
    result.setName(warrior.getName());
    result.setNameExhibition(warrior.getName()+"xyz");
    result.setHairType(warrior.getHairType());
    result.setHairColor(warrior.getHairColor());
    result.setArmor(warrior.getArmor());
    result.setWeapon(warrior.getWeapon());

    return result;
  }
  
}

**Comment by npathai** [comment]
@jrxxjr Apologies for not being able to reply for long time. I will review this soon and let you know of any changes required.

**Comment by iluwatar** [comment]
This pull request is about to be closed due to inactivity

**Pull request closed without merging**
