### PR TITLE
#509: Component Object Pattern

### PR DESCRIPTION
**Pull request by nikhilbarar**
An implementation of Component Object Pattern using IBM Selenium.

Added a new module 'component-object'.

### CODE REVIEW

**Comment by iluwatar** [comment]
@nikhilbarar the PR has conflicts that should be resolved

**Comment by npathai** [comment]
@nikhilbarar Are you still working on it? Else we will have to close the PR due to inactivity

**Comment by iluwatar** [comment]
This pull request is about to be closed due to inactivity

**Comment by iluwatar** [comment]
@all-contributors please add @nikhilbarar for code

**Pull request closed without merging**
