### PR TITLE
Bytecode pattern #553

### PR DESCRIPTION
**Pull request by pzawitowski**
Implementation of Bytecode pattern in accordance with http://gameprogrammingpatterns.com/bytecode.html

### CODE REVIEW

**Comment by iluwatar** [comment]
There are conflicts, please fix

**Comment by pzawitowski** [comment]
I've resolved conflicts.

**Comment by iluwatar** [comment]
Still conflicting @pzawitowski

**Comment by pzawitowski** [comment]
Conflicts fixed.

**Comment by iluwatar** [comment]
Good job @pzawitowski :+1: Thank you for the new pattern! :smiley:

**Pull request merged**
