### PR TITLE
Async method invocation

### PR DESCRIPTION
**Pull request by trautonen**
Implementation of #68.

I don't have eclipse installed so couldn't create the UML class diagram.

### CODE REVIEW

**Comment by iluwatar** [comment]
Thanks Tapio! I will look into this.

**Comment by iluwatar** [comment]
The code is excellent. Exemplary work!

**Comment by iluwatar** [comment]
I added the class diagram.

**Comment by iluwatar** [comment]
Tapio, do have an idea why #104 occurs?

**Comment by trautonen** [comment]
I'll try to look on that tonight.

**Pull request merged**
