### PR TITLE
Modified IT README file (#2314)

### PR DESCRIPTION
**Pull request by girolamo-giordano**
Correct some languages and syntax errors inside the IT README file

### CODE REVIEW

**Comment by iluwatar** [comment]
Please rebase on top of master branch. Let's see if that fixes the sonar issue...

**Comment by girolamo-giordano** [comment]
Still not working, same error.

**Comment by iluwatar** [comment]
@girolamo-giordano please bear with me, but could you again rebase and try? I made a small change again.

**Comment by girolamo-giordano** [comment]
@iluwatar Now works, test passed

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Thank you @girolamo-giordano for the translation and all your help in solving the Sonar issue!

@all-contributors please add @girolamo-giordano for translation

**Pull request merged**
