### PR TITLE
fix: Refactor Layered Architecture pattern #2936

### PR DESCRIPTION
**Pull request by romannimets**
## What problem does this PR solve?

Ecco un possibile testo che potresti aggiungere nella tua pull request:

---

## What problem does this PR solve?

This PR addresses a couple of specific issues in the Layered Architecture code example (#2936):

1. **Main Entry Point for Runner.java**: Runner.java lacked a main entry point, preventing it from being executed directly in an IDE. This PR adds a `main` method to Runner.java to resolve this issue.

2. **Warnings Regarding Optional Usage**: There were warnings related to the usage of `Optional` as a type for the `id` field in the classes `CakeInfo`, `CakeLayerInfo`, and `CakeToppingInfo`. The use of `Optional` for fields is generally discouraged, as `Optional` is primarily intended for method return types where there is a need to represent "no result" without using null.

I'm relatively new to contributing and may have misunderstood or not fully addressed the issues. If there are any mistakes or if further changes are needed, please let me know. Apologies for any inconvenience caused.

### CODE REVIEW

**Comment by iluwatar** [comment]
Let me know when it's ready for review

**Review by iluwatar — DISMISSED** [review]

**Comment by iluwatar** [comment]
Sorry, I have missed the notification that this PR is ready for review. If you could fix the conflicts then we are ready to merge @romannimets

**Comment by romannimets** [comment]
Sorry @iluwatar i may have made some mistakes during the conflict solving process 😅, i hope now everything is all right. Thaks for the patience

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Looks good! Thank you for the contribution 🎉

@all-contributors please add @romannimets for code

**Pull request merged**
