### PR TITLE
Leader Election Pattern

### PR DESCRIPTION
**Pull request by Azureyjt**
This PR fixes issue #447 

Implemented leader election pattern with the following algorithm:

- Token-ring 
- Bully

### CODE REVIEW

**Comment by Azureyjt** [comment]
@iluwatar Please kindly review this PR.

**Comment by iluwatar** [comment]
There is a conflict that must be resolved

**Comment by Azureyjt** [comment]
> There is a conflict that must be resolved

Conflict fixed.

**Comment by iluwatar** [comment]
Well done @Azureyjt, such a nice pattern :rose:

**Pull request merged**
