### PR TITLE
#1021: Fix checkstyle warnings by changing the license header template

### PR DESCRIPTION
**Pull request by vanogrid**
Issue #1021 

Google's Checkstyle ruleset doesn't play well with the javadoc license headers, because it demands the first line to have a dot at the end, a `<p>` tag at the beginning of a paragraph, etc. 

I changed the license header style to the `SLASHSTAR_STYLE`, provided with the license-maven-plugin (which is also the default one now, but after v3.0 there is no new release yet). Checkstyle didn't like that one either and wanted the package name to be "separated from the previous statement" by a blank line, so I ended up creating a custom license header with this blank line added (license-plugin-header-style.xml). This fixed the issues with the license header. There were minimal changes in the code and now the Checkstyle warnings are less than half (2,8k). The issue is not done yet, but this should be a good start.

### CODE REVIEW

**Comment by iluwatar** [comment]
@vanogrid thanks, this is a great step forward in solving that issue!

**Comment by iluwatar** [comment]
New problem was detected, see https://github.com/iluwatar/java-design-patterns/issues/1037

**Comment by vanogrid** [comment]
Sorry about that, I will have a look asap.

**Comment by iluwatar** [comment]
No problem @vanogrid. Thanks for looking into it :+1:

**Pull request merged**
