### PR TITLE
First proposal for #586 Hexagonal Architecture primary ports should have interfaces

### PR DESCRIPTION
**Pull request by 7agustibm**
It's a first proposal add interface primary ports for this issue #586.

I have adapted the ConsoleLottery with LotteryService Interface and implemented this. The ConsoleLottery create a new instance of LotteryServiceImpl and move this logic in the LotteryServiceImpl.

Maybe it's not a the best name for this class, but if you like the implementation, I will adapt the names of the classes and do the same with ConsoleAdministration.

@iluwatar Do you like this adaptation for Hexagonal Architecture with interface?

### CODE REVIEW

**Comment by iluwatar** [comment]
@7agustibm any updates?

**Comment by 7agustibm** [comment]
Yes. You have the new proposal.  What do you think?

**Comment by 7agustibm** [comment]
Sorry. Yes, you have a new version.
What do you think?

**Comment by iluwatar** [comment]
@7agustibm the changes look good and implement the task as requested. Good job :+1:

The next step is to modify the blog post http://java-design-patterns.com/blog/build-maintainable-systems-with-hexagonal-architecture/ accordingly. Please make another pull request for that. You need to modify the gh-pages branch, see instructions here https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute.

**Pull request merged**
