### PR TITLE
#297 Create API Gateway pattern

### PR DESCRIPTION
**Pull request by TylerMcConville**
This pattern showcases an API Gateway calling 2 different microservices - one for images, and one for prices.

I created the image and price microservices as submodules of the API Gateway. I needed them to be their own distinct JARs, but also keep them a part of the API Gateway pattern. If there is a better way to do this, please let me know.

The API Gateway and microservices run with Spring Boot. To run them, first build each one by running `mvn package` from the appropriate folder (the api-gateway, price-microservice, or image-microservice folder). That command should create a JAR file in the "target" folder. Run `java -jar target/jar-name.jar` - that should start Spring Boot. You will need to do this for the API Gateway, the Price microservice, and the Image microservice.

Once both microservices and the API Gateway are running, you can test it out by hitting "localhost:50004/desktop" or "localhost:50004/mobile".

### CODE REVIEW

**Comment by iluwatar** [comment]
@TylerMcConville in general, it looks really good and works as you instructed. Here are my review comments:
- License headers are missing from some of the files. You can autogenerate them with `mvn clean install`
- In `README.md` I would assign `Architectural` category and `Difficulty-Intermediate` and `Spring` tags
- At the moment the microservices submodules are not built when api-gateway module is built.
- Please move the dependencies to the parent `pom.xml` and only reference them in api-gateway `pom.xml`

**Comment by iluwatar** [comment]
That's it, you have my review remarks. Please comment once you've addressed them and I'll take another look.

**Comment by TylerMcConville** [comment]
@iluwatar I have implemented all of your feedback. The structure has changed a bit: there's a new submodule, api-gateway-service, that contains the code to run the API Gateway itself. The api-gateway parent module now has a packaging type of "pom" and will build all 3 submodules when it is built.

So the updated instructions to run it are:

- Run `mvn package` from the parent module (api-gateway)
- From each of the 3 submodules, in the `target` directory, run `java -jar jar-name.jar`

**Comment by iluwatar** [comment]
@TylerMcConville look perfect! Thanks a lot for the contribution :+1:

**Comment by iluwatar** [comment]
@all-contributors please add @TylerMcConville for code

**Pull request merged**
