### PR TITLE
Fix #216 Repository vs DAO

### LINKED ISSUE #216: Repository vs DAO
I think that Repository pattern is not implemented in the correct way and it looks like DAO. Here is a good article about this http://thinkinginobjects.com/2012/08/26/dont-use-dao-use-repository/

### PR DESCRIPTION
**Pull request by hoswey**
Please review.

### CODE REVIEW

**Comment by iluwatar** [comment]
This looks perfect. Thank you @hoswey !

**Comment by neonds** [comment]
Hi, every one. Hoswey I saw that you use Spring Data. Maybe is a good idea to use a Spring annotation based config too.

https://github.com/hoswey/java-design-patterns/pull/1/files

**Comment by iluwatar** [comment]
Hi @neonds why not make a pull request against the master branch?

**Comment by neonds** [comment]
Okay ;)

**Pull request merged**
