### PR TITLE
Optimized NioReactor stop() (Reactor Pattern)

### PR DESCRIPTION
**Pull request by yuhangbin**
Optimize the closing mode of reactorMain(class: ExecutorService).
Ensure that reactorMain closes on time.

Please see the code.

Reference:
- https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ExecutorService.html

### CODE REVIEW

**Comment by iluwatar** [comment]
@ohbus I would appreciate your consultation here. Do you have any idea why CircleCI test fails here?

**Review by iluwatar — CHANGES_REQUESTED** [review]
The build is failing due to Checkstyle issue

**Comment by ohbus** [comment]
> @ohbus I would appreciate your consultation here. Do you have any idea why CircleCI test fails here?

You're right about the check styles.

We have 3 builds checking the same code, all of them must not fail.

**Comment by iluwatar** [comment]
> No Sonar PR analysis as this is not a pull request

**Comment by yuhangbin** [comment]
> The build is failing due to Checkstyle issue

I can't find checkstyle.xml file in master branch. Where do I get checkstyle.xml?

**Comment by yuhangbin** [comment]
I already use Google checkstyle.xml.

**Comment by yuhangbin** [comment]
@ohbus @iluwatar Help me to run workflows. Thanks!

**Review by iluwatar — APPROVED** [review]

**Comment by iluwatar** [comment]
Thank you for the valuable improvement!
@all-contributors please add @yuhangbin for code

**Pull request merged**
