### PR TITLE
[refactor] Makes enums more readable.

### PR DESCRIPTION
**Pull request by ruslanpa**

### CODE REVIEW

**Comment by iluwatar** [comment]
Hey, that's a great idea. Can you apply this across all the patterns, where applicable, please?

**Comment by ruslanpa** [comment]
Yes, I can do this. It is in progress now.

**Comment by iluwatar** [comment]
Excellent. Please let me know when you are done.

**Comment by ruslanpa** [comment]
I did it, check my pull request.

**Pull request merged**
