### PR TITLE
#466: Monitor object

### PR DESCRIPTION
**Pull request by nikhilbarar**
An implementation of Monitor Object Pattern.

Added a new module 'monitor-object'.

### CODE REVIEW

**Comment by iluwatar** [comment]
@nikhilbarar the PR has conflicts that should be resolved

**Comment by iluwatar** [comment]
@nikhilbarar please indicate if you are still working on this. Otherwise it will be closed.

**Comment by nikhilbarar** [comment]
@iluwatar Yes, I'll resolve the conflicts and update

**Comment by iluwatar** [comment]
@nikhilbarar The code looks great and the tests work. By convention we have included `App.java` in the examples that provides a starting point for the example. In that file please provide a description what the example does so it is easy for the reader to start studying. See the other patterns for an example.

**Comment by iluwatar** [comment]
- Could you add little description to `App.java` as well so the reader can comprehend the example more quickly?
- Can you add `AppTest.java` that tests that running the `App.java` succeeds? This is a convention used in other examples too.

**Comment by npathai** [comment]
@nikhilbarar You have done great job here, any update? I don't want this PR to die :disappointed:

**Comment by nikhilbarar** [comment]
@npathai Apologies for the late response. I'm working on this and will update it in a couple of days.

**Comment by iluwatar** [comment]
This pull request is about to be closed due to inactivity

**Pull request closed without merging**
