### PR TITLE
Adds criticism to a Service Locator and Singleton patterns.

### LINKED ISSUE #436: Add criticism to Service Locator
More information could be added to `Consequences` section of the Service Locator pattern.

http://criticalsoftwareblog.com/index.php/2015/10/25/object-composability-another-reason-why-the-service-locator-is-an-anti-pattern/

See the pattern template here: https://github.com/iluwatar/java-design-patterns/wiki/02.-Pattern-template

### PR DESCRIPTION
**Pull request by dmitraver**
Fixes #436, #437. 

Lists drawbacks of the Service Locator and Singleton patterns.

### CODE REVIEW

**Comment by dmitraver** [comment]
@iluwatar 

Hi! Please review once you have a time ;)

**Comment by dmitraver** [comment]
Yeah, I reread it also after a while and it doesn't ring a bell. I will make a change today and update my PR. Thanks.

**Comment by dmitraver** [comment]
@iluwatar I addressed your points. I removed the phrase that causes confusion cause its an edge case of singleton usage and its already described better in other two points. What do you think?

**Comment by iluwatar** [comment]
@dmitraver looks good now. Thanks for your contribution!

**Pull request merged**
