### PR TITLE
issue #333 Factory-kit

### PR DESCRIPTION
**Pull request by Crossy147**
I've tried my best to show simplicity of a Factory-kit pattern using Java8 Functional Interface.
I'm sorry for accidentally changing and reverting Factory-method test's class code style.

### CODE REVIEW

**Comment by iluwatar** [comment]
Review remarks:
- Please add description to `App.java` that describes the pattern and implementation like in the other examples

**Comment by iluwatar** [comment]
@Crossy147 you have my review comments. Please notify once you have made the changes.

**Comment by Crossy147** [comment]
ok, i've included review comments

**Comment by iluwatar** [comment]
Great work @Crossy147 Thank you for the contribution!

**Comment by npathai** [comment]
Thanks @Crossy147  for the contribution.

**Pull request merged**
