### PR TITLE
Monad pattern

### PR DESCRIPTION
**Pull request by Crossy147**
Monad pattern introduced. Shown as an instance of step-by-step validator.

### CODE REVIEW

**Comment by iluwatar** [comment]
@Crossy147 the build is failing:

`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:testCompile (default-testCompile) on project monad: Compilation failure: Compilation failure:
[ERROR] /home/travis/build/iluwatar/java-design-patterns/monad/src/test/java/com/iluwatar/monad/MonadTest.java:[27,18] cannot find symbol
[ERROR] symbol:   variable tom`

**Comment by iluwatar** [comment]
Please add description of the pattern and implementation notes to `App.java` as in the other examples.

**Comment by Crossy147** [comment]
ok, it's done :)

**Comment by iluwatar** [comment]
Thank you @Crossy147 This is a great example :+1:

**Comment by npathai** [comment]
@Crossy147 @iluwatar I am sorry to be late at this a few points:
 - bind is also called flatMap in some languages such as scala.
 - Java8 Optional can also be called a Monadic class. https://gist.github.com/ms-tg/7420496#file-jdk8_optional_monad_laws-java

If you guys confirm then I will add the changes to `index.md` and commit it to master.

**Comment by BerserkerTroll** [comment]
> based on monad from linear algebra 
@Crossy147 are you sure?

**Comment by Crossy147** [comment]
@BerserkerTroll indeed, the idea is not based on the linear algebra's one. The concept comes from category theory instead. source: https://en.wikipedia.org/wiki/Monad_(functional_programming)

**Pull request merged**
