### PR TITLE
issue 102 - Fixing few SonarQube critical issues.

### PR DESCRIPTION
**Pull request by mookkiah**
Issue 102: Fixing few SonarQube critical issues.

- Existing code uses String concatination using plus operator
- New change uses SL4J formatter option.

Pull request description

- This should remove some critical issues in SonarQube.

> For detailed contributing instructions see https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute

### CODE REVIEW

**Comment by mookkiah** [comment]
@iluwatar I made change only in commander/src/main/java/com/iluwatar/commander/Commander.java.
But the build failed at trampoline/src/main/java/com/iluwatar/trampoline/Trampoline.java which I guess not related to this PR.

Anyway I will check and let you know.

**Comment by mookkiah** [comment]
Created another PR #1529  for fixing issue in Trampoline module. This PR check needs to be triggered after that is merged.

**Comment by iluwatar** [comment]
@mookkiah please merge the changes from `master` and we should see the PR build turn green

**Comment by mookkiah** [comment]
@iluwatar Do you want me to merge my changes to mookkiah:master the create PR to iluwatar:master?

**Comment by mookkiah** [comment]
I see @ohbus opened an issue #1537 and PR #1538 for the same  build problem.

**Pull request closed without merging**
