### PR TITLE
Model-View-ViewModel Design Pattern

### PR DESCRIPTION
**Pull request by jinishavora**
MVVM is a design pattern commonly used in Android, along with Databinding and Gradle is used for the build process.

The attempt in this code has been to create similar project in Maven, but I couldn't find databinding related setup in Maven as similar to that of gradle.

This code will not compile as the dependencies for databinding couldn't resolve as android dependencies in Maven is not commonly found or implemented.

Any suggestions as to how to go about this would be helpful.

### CODE REVIEW

**Review by ohbus — CHANGES_REQUESTED** [review]
The project is not configured like a Maven project.

Also you need to add this module to the parent pom to check if it is working

**Comment by ohbus** [comment]
> MVVM is a design pattern commonly used in Android, along with Databinding and Gradle is used for the build process.
> 
> The attempt in this code has been to create similar project in Maven, but I couldn't find databinding related setup in Maven as similar to that of gradle.
> 
> This code will not compile as the dependencies for databinding couldn't resolve as android dependencies in Maven is not commonly found or implemented.
> 
> Any suggestions as to how to go about this would be helpful.

Puttings java files under `src/main/java`
And resources files like `src/main/resources`  

This might help in getting along with the compilation process.

**Comment by jinishavora** [comment]
> The project is not configured like a Maven project.
> 
> Also you need to add this module to the parent pom to check if it is working

**Comment by jinishavora** [comment]
There was a reason I didn't add it, I have now added it and you can see the maven build fail, because of dependencies and I couldn't get those dependencies to work, also, if project structure was the only thing required to compile the files, I would have definitely done that, but that is not the case here.

**Comment by jinishavora** [comment]
The build failing due to androidx dependencies, can be fixed by adding android sdk path and maven google url into settings.xml inside .m2 folder. (Although have removed the androidx dependencies from the project for now.)

<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
  <profiles>
    <profile>
        <id>android-settings</id>
        <properties>
            <android.sdk.path>C:\Users\Jinisha\AppData\Local\Android\Sdkwithtools</android.sdk.path>
        </properties>
    </profile>
    <profile>
      <id>google</id>
      <repositories>
        <repository>
          <id>google</id>
          <name>Google</name>
          <snapshots>
            <enabled>true</enabled>
            <checksumPolicy>fail</checksumPolicy>
          </snapshots>
          <url>https://maven.google.com</url>
        </repository>
      </repositories>
    </profile>
  </profiles>
  <activeProfiles>
        <activeProfile>google</activeProfile>
        <activeProfile>android-settings</activeProfile>
  </activeProfiles>
</settings>

**Review by ohbus — CHANGES_REQUESTED** [review]
If you would want the build to have android environment to execute your code properly we have it or maybe separate it on the basis of need if required.

But the current build seems to not have any test cases written to it the reason why there is no coverage report that is generated as well.

Below is the build log of your module.
```console
[INFO] -----------------< com.iluwatar:model-view-viewmodel >------------------
[INFO] Building model-view-viewmodel 1.24.0-SNAPSHOT                  [150/150]
[INFO] --------------------------------[ pom ]---------------------------------
Downloading from jitpack.io: https://jitpack.io/com/google/android/android/4.1.1.4/android-4.1.1.4.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/google/android/android/4.1.1.4/android-4.1.1.4.pom
Progress (1): 2.7/2.9 kB
Progress (1): 2.9 kB    
                    
Downloaded from central: https://repo.maven.apache.org/maven2/com/google/android/android/4.1.1.4/android-4.1.1.4.pom (2.9 kB at 25 kB/s)
Downloading from jitpack.io: https://jitpack.io/org/khronos/opengl-api/gl1.1-android-2.1_r1/opengl-api-gl1.1-android-2.1_r1.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/khronos/opengl-api/gl1.1-android-2.1_r1/opengl-api-gl1.1-android-2.1_r1.pom
Progress (1): 1.6 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/khronos/opengl-api/gl1.1-android-2.1_r1/opengl-api-gl1.1-android-2.1_r1.pom (1.6 kB at 54 kB/s)
Downloading from jitpack.io: https://jitpack.io/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.pom
Downloading from central: https://repo.maven.apache.org/maven2/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.pom
Progress (1): 153 B
                   
Downloaded from central: https://repo.maven.apache.org/maven2/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.pom (153 B at 5.7 kB/s)
Downloading from jitpack.io: https://jitpack.io/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.pom
Downloading from central: https://repo.maven.apache.org/maven2/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.pom
Progress (1): 2.1 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.pom (2.1 kB at 81 kB/s)
Downloading from jitpack.io: https://jitpack.io/org/json/json/20080701/json-20080701.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/json/json/20080701/json-20080701.pom
Progress (1): 1.7 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/json/json/20080701/json-20080701.pom (1.7 kB at 60 kB/s)
Downloading from jitpack.io: https://jitpack.io/org/projectlombok/lombok/1.18.16/lombok-1.18.16.pom
Downloading from central: https://repo.maven.apache.org/maven2/org/projectlombok/lombok/1.18.16/lombok-1.18.16.pom
Progress (1): 1.5 kB
                    
Downloaded from central: https://repo.maven.apache.org/maven2/org/projectlombok/lombok/1.18.16/lombok-1.18.16.pom (1.5 kB at 53 kB/s)
Downloading from jitpack.io: https://jitpack.io/com/google/android/android/4.1.1.4/android-4.1.1.4.jar
Downloading from jitpack.io: https://jitpack.io/org/khronos/opengl-api/gl1.1-android-2.1_r1/opengl-api-gl1.1-android-2.1_r1.jar
Downloading from jitpack.io: https://jitpack.io/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.jar
Downloading from jitpack.io: https://jitpack.io/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.jar
Downloading from jitpack.io: https://jitpack.io/org/json/json/20080701/json-20080701.jar
Downloading from jitpack.io: https://jitpack.io/org/projectlombok/lombok/1.18.16/lombok-1.18.16.jar
Downloading from central: https://repo.maven.apache.org/maven2/com/google/android/android/4.1.1.4/android-4.1.1.4.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/khronos/opengl-api/gl1.1-android-2.1_r1/opengl-api-gl1.1-android-2.1_r1.jar
Downloading from central: https://repo.maven.apache.org/maven2/org/json/json/20080701/json-20080701.jar
Downloading from central: https://repo.maven.apache.org/maven2/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.jar
Downloading from central: https://repo.maven.apache.org/maven2/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/khronos/opengl-api/gl1.1-android-2.1_r1/opengl-api-gl1.1-android-2.1_r1.jar (18 kB at 260 kB/s)
Downloading from central: https://repo.maven.apache.org/maven2/org/projectlombok/lombok/1.18.16/lombok-1.18.16.jar
Downloaded from central: https://repo.maven.apache.org/maven2/org/projectlombok/lombok/1.18.16/lombok-1.18.16.jar (1.9 MB at 6.3 MB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/com/google/android/android/4.1.1.4/android-4.1.1.4.jar (13 MB at 21 MB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/json/json/20080701/json-20080701.jar (38 kB at 35 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/xpp3/xpp3/1.1.4c/xpp3-1.1.4c.jar (120 kB at 110 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/xerces/xmlParserAPIs/2.6.2/xmlParserAPIs-2.6.2.jar (125 kB at 114 kB/s)
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ model-view-viewmodel ---
[INFO] 
[INFO] --- maven-checkstyle-plugin:3.1.0:check (validate) @ model-view-viewmodel ---
[INFO] 
[INFO] --- directory-maven-plugin:0.3.1:directory-of (directories) @ model-view-viewmodel ---
[INFO] Directory of com.iluwatar:java-design-patterns set to: /home/runner/work/java-design-patterns/java-design-patterns
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:prepare-agent (prepare-agent) @ model-view-viewmodel ---
[INFO] argLine set to -javaagent:/home/runner/.m2/repository/org/jacoco/org.jacoco.agent/0.8.6/org.jacoco.agent-0.8.6-runtime.jar=destfile=/home/runner/work/java-design-patterns/java-design-patterns/model-view-viewmodel/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:copy-resources (default) @ model-view-viewmodel ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/runner/work/java-design-patterns/java-design-patterns/model-view-viewmodel/src/templates/res
[INFO] 
[INFO] --- android-maven-plugin:4.0.0-rc.2:manifest-update (manifestUpdate) @ model-view-viewmodel ---
[INFO] 
[INFO] --- urm-maven-plugin:1.4.8:map (default) @ model-view-viewmodel ---
15:09:14,140 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
15:09:14,140 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
15:09:14,140 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/home/runner/.m2/repository/com/iluwatar/urm/urm-core/1.4.8/urm-core-1.4.8.jar!/logback.xml]
15:09:14,151 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@744ceff1 - URL [jar:file:/home/runner/.m2/repository/com/iluwatar/urm/urm-core/1.4.8/urm-core-1.4.8.jar!/logback.xml] is not of type file
15:09:14,167 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
15:09:14,167 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
15:09:14,173 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
15:09:14,195 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - This appender no longer admits a layout as a sub-component, set an encoder instead.
15:09:14,195 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
15:09:14,195 |-WARN in ch.qos.logback.core.ConsoleAppender[CONSOLE] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
15:09:14,196 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.iluwatar.urm] to INFO
15:09:14,196 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting additivity of logger [com.iluwatar.urm] to false
15:09:14,196 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[com.iluwatar.urm]
15:09:14,197 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
15:09:14,197 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to Logger[ROOT]
15:09:14,197 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:09:14,197 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@7ac4947c - Registering current configuration as safe fallback point

[INFO] model-view-viewmodel.urm.puml already exists, file was not overwritten!
[INFO] 
[INFO] --- android-maven-plugin:4.0.0-rc.2:zipalign (alignApk) @ model-view-viewmodel ---
[INFO] Skipping zipalign on pom
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.6:report (report) @ model-view-viewmodel ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
```
_I can see the URM is not being created due to obvious reasons nor can the test execution data can be generated_

As I do not have good expertise over Android, but I do understand that this can be achieved while working out the pattern in maven build as well.

Have you explored if there are certain maven archetype which would help you bootstrap this artifact. Something like [this](https://mvnrepository.com/artifact/de.akquinet.android.archetypes)

**Comment by ohbus** [comment]
@xiaod-dev has got some Android experience, I can request a review from him.

And I would also request @iluwatar to share some insight on this.

**Review by iluwatar — CHANGES_REQUESTED** [review]
Thank you for working on this new pattern @jinishavora. MVVM is a relatively simple pattern and I would like to see the example being a simple one too. At the moment there's the Android-related stuff accommodating 80% of the pull request and I would like to get rid of that. I suggest we implement this example as a bare-bones Maven-based Java application. Essentially, I think we are going to need around 5 Java classes for the whole example.

**Comment by jinishavora** [comment]
@iluwatar Thank you for your suggestion, I started out to create a bare-bones Maven based Java application depicting MVVM pattern, but I couldn't find any relevant documentation/suggestion/implementation online to successfully achieve it.
I have usually implemented MVVM only in Gradle based java project and never for maven based java application, on looking through stackoverflow and all the other resources online, I still couldn't find anything on the lines of what we intend to implement here.

Only resources I found other than android (gradle) based java project and .NET are:

https://dzone.com/articles/test-driving-mvvm-pattern-zk-0
https://jaxenter.com/mvvmfx-model-view-viewmodel-javafx-114907.html

But nothing in terms of straight forward Java implementation as maven project for MVVM depiction.
If you have any reference or any source based on which the suggestion is made, I would be happy to look into it and implement accordingly.

**Comment by iluwatar** [comment]
> But nothing in terms of straight forward Java implementation as maven project for MVVM depiction.
> If you have any reference or any source based on which the suggestion is made, I would be happy to look into it and implement accordingly.

Browsing the project issues I found that we have 3 separate ones for this task and they contain some good references as well. @jinishavora please take a look at these issues and their comments:

- https://github.com/iluwatar/java-design-patterns/issues/1215
- https://github.com/iluwatar/java-design-patterns/issues/601
- https://github.com/iluwatar/java-design-patterns/issues/61

Good news is that by implementing this pattern you can actually close 3 tasks 🙂

**Comment by jinishavora** [comment]
@iluwatar Thanks!
Links in #601 looks promising, let me check it out, although they are referring to some framework, but I have a feeling it would still be close to what we are trying to achieve.

**Pull request closed without merging**
