### PR TITLE
Update site pages to render syntax highlighting #728

### PR DESCRIPTION
**Pull request by Deathnerd**
Used in conjunction with changes in  #730 

- Add syntax highlighting stylesheet
- Enabled syntax highlighting in Jekyll config settings
- Added the syntax highlighter gem to the Gemfile

### CODE REVIEW

**Comment by Deathnerd** [comment]
Weird. Looks like the Travis job was flaky somehow? I don't think it's related to anything I did

**Comment by iluwatar** [comment]
Thanks @Deathnerd for the improvements! Very much appreciated :+1:

**Comment by Deathnerd** [comment]
No problem! Happy to help! 

Could we possibly put a requirement on the wiki to mark preformatted blocks with their language wherever possible? If only for consistency's sake

**Comment by iluwatar** [comment]
@Deathnerd thanks, I've now updated https://github.com/iluwatar/java-design-patterns/wiki/01.-How-to-contribute and https://github.com/iluwatar/java-design-patterns/wiki/08.-Reviewing-pull-requests to remind about `README.md` syntax highlighting.

**Comment by Deathnerd** [comment]
Awesome! It's been a pleasure and a breeze to work with you guys on this repo. I'll definitely look for other ways to contribute in the future. This is an invaluable resource and I'll be recommending it to my students in the future for sure

**Pull request merged**
