### PR TITLE
Updated ThreadSafeLazyLoadedivoryTower

### PR DESCRIPTION
**Pull request by shaiktaj**
Added null check in private constructor to prevent instantiating by Reflection call

### CODE REVIEW

**Comment by iluwatar** [comment]
@shaiktaj  this pull request is about to be closed due to inactivity. Please comment if you are still working on this.

**Comment by shaiktaj** [comment]
@iluwatar The IllegalStateException is being thrown right?

**Comment by iluwatar** [comment]
Thanks @shaiktaj it looks good :+1:

**Comment by igorcadelima** [comment]
It's still possible to create many instances of the class using only reflection.

**Comment by iluwatar** [comment]
It is not a complete solution, but a step in the right direction. See https://stackoverflow.com/questions/6994393/singleton-how-to-stop-create-instance-via-reflection/6994437

**Pull request merged**
