### PR TITLE
Leader Follower initial commit

### PR DESCRIPTION
**Pull request by amit2103**
Pull request for issue #179 (Leader Follower Pattern). Made some changes as per feedback. In order to reduce merge conflicts making this new request

### CODE REVIEW

**Comment by iluwatar** [comment]
@amit2103 it looks quite good but the conflict needs to be resolved before it can be merged.

**Comment by amit2103** [comment]
@iluwatar  Okay..Will update the branch

**Comment by iluwatar** [comment]
@amit2103 the conflicts still persist.

**Comment by amit2103** [comment]
@iluwatar  resolved..will update by Tuesday

**Comment by amit2103** [comment]
@iluwatar updated...please look at this now .

**Comment by iluwatar** [comment]
@amit2103 the Leader-Follower itself looks quite good but the changelist contains huge amount of changes to other patterns. Please revert the unnecessary changes.

**Comment by amit2103** [comment]
Is it possible to cherry pick? It seems the changes are added from the
rebase, as I Definitely didnt change the files

**Comment by iluwatar** [comment]
@amit2103 you can reset the files you didn't want to change by checking them out from `master` branch. For example `git checkout master -- api-gateway/README.md` would reset one file.

**Comment by amit2103** [comment]
Okay...Will try this today.

**Comment by iluwatar** [comment]
@amit2103 final call, I'm about to close this pull request due to inactivity.

**Comment by amit2103** [comment]
Apologies for the delay..I will get this done by tomorrow...

**Comment by amit2103** [comment]
@iluwatar  Do you know why I keep getting this updates when I am rebasing the origin..I was trying to do it again..But saw some changes?  Is there a way to avoid it

**Comment by iluwatar** [comment]
Hey @amit2103 what are trying to do? Maybe this helps https://help.github.com/articles/syncing-a-fork/

**Comment by amit2103** [comment]
I tried to rebase , let me try merge

**Comment by iluwatar** [comment]
First merge master, then use the checkout command to reset the unwanted changes as I wrote before.

**Comment by iluwatar** [comment]
I'm closing this pull request due to inactivity.

**Comment by iluwatar** [comment]
@all-contributors please add @amit2103 for code

**Pull request closed without merging**
