### PR TITLE
Update to JUnit5 across all modules

### PR DESCRIPTION
**Pull request by charlesfinley**
Update to JUnit5 across all modules

This PR updates the project to JUnit 5 across the board with 1 or 2 exceptions where there are conflicts with some existing tests.

### CODE REVIEW

**Comment by charlesfinley** [comment]
I opened Issue #1667 to track the modules that cannot be upgraded at this time.

**Review by ohbus — COMMENTED** [review]
@charlesfinley did you rebase this branch with the master?

**Comment by charlesfinley** [comment]
> @charlesfinley did you rebase this branch with the master?

Yes - this branch is current with master.

**Comment by iluwatar** [comment]
Looks good to me.

> This PR updates the project to JUnit 5 across the board with 1 or 2 exceptions where there are conflicts with some existing tests.

@charlesfinley Can you point out these exceptions so we can potentially create a new issue about fixing them?

**Comment by charlesfinley** [comment]
> Looks good to me.
> 
> > This PR updates the project to JUnit 5 across the board with 1 or 2 exceptions where there are conflicts with some existing tests.
> 
> @charlesfinley Can you point out these exceptions so we can potentially create a new issue about fixing them?

I've opened Issue #1667 and #1669

**Comment by iluwatar** [comment]
Excellent, thank you!  🎉

**Review by ohbus — APPROVED** [review]
Thank you @charlesfinley for upgrading the code and reporting issues with the existing ones.

Your continuous effort helps makes this project an awesome one.

**Pull request merged**
